### PR TITLE
Add tests for Promise.all|race resolve lookup

### PR DESCRIPTION
**Pull request by leobalter**
Ref tc39/ecma262#1506

The proposed spec needs consensus, please don't merge this yet.

### CODE REVIEW

**Comment by gsathya** [comment]
Thanks, I ran these against [V8's implementation](https://chromium-review.googlesource.com/c/v8/v8/+/1574705) and they all pass!

But, the following test262 tests need updating as well:
```
  'built-ins/Promise/all/capability-executor-called-twice': [FAIL],
  'built-ins/Promise/all/capability-resolve-throws-no-close': [FAIL],
  'built-ins/Promise/all/capability-resolve-throws-reject': [FAIL],
  'built-ins/Promise/all/invoke-resolve-get-error-close': [FAIL],
  'built-ins/Promise/all/species-get-error': [FAIL],
  'built-ins/Promise/race/capability-executor-called-twice': [FAIL],
  'built-ins/Promise/race/invoke-resolve-get-error-close': [FAIL],
  'built-ins/Promise/race/species-get-error': [FAIL],
```

**Comment by leobalter** [comment]
Thanks! I'll take a look at these and any potentially matching for allSettled

**Comment by gsathya** [comment]
> Thanks! I'll take a look at these and any potentially matching for allSettled

These are the failing allSettled ones --

```
  'built-ins/Promise/allSettled/capability-executor-called-twice': [FAIL],                                                                                    
  'built-ins/Promise/allSettled/capability-resolve-throws-no-close': [FAIL],                                                                                  
  'built-ins/Promise/allSettled/capability-resolve-throws-reject': [FAIL],
  'built-ins/Promise/allSettled/invoke-resolve-get-error-close': [FAIL],
  'built-ins/Promise/allSettled/reject-element-function-name': [FAIL],
  'built-ins/Promise/allSettled/resolve-element-function-name': [FAIL],
  'built-ins/Promise/allSettled/species-get-error': [FAIL],                                                                                                   
```

**Comment by leobalter** [comment]
tests are up, thanks for reporting the errors! I also caught some new false positives that are not prevented in the modified tests.

**Comment by leobalter** [comment]
CircleCI is giving a false positive for the tests execution due to an upgrade on Test262's version that requires another upgrade on Test262-harness that is planned to be updated soon.

**Comment by leobalter** [comment]
@gsathya would you take a look, please? I can tell from local runs the only tests I'm getting errors are the ones related to the function name.

**Comment by gsathya** [comment]
All tests pass on ToT v8 🔥

**Pull request merged**
