### PR TITLE
Replace runTestCase when used with try-finally

### PR DESCRIPTION
**Pull request by anba**
Do we care at all about restoring built-ins after tests have finished? If it's not important or required to restore built-ins, the `finally` blocks in these tests can be removed. But for the time being I've left them there.

### CODE REVIEW

**Comment by jugglinmike** [comment]
It's a good question. If we do, the safe approach requires enough code to maybe warrant a helper function:

```js
function extendBuiltin(builtin, prop, value, cb) {
  var original = builtIn[prop];
  var wasDefined = Object.hasOwnProperty.call(original, prop);

  builtIn[prop] = value;

  try {
    cb();
  } finally {
    if (wasDefined) {
      builtIn[prop] = original;
    } else {
      delete builtIn[prop];
    }
  }
}
```

**Comment by domenic** [comment]
We almost certainly do not. The tests explicitly each run in a clean context.

**Comment by bterlson** [comment]
Not necessary IMO. Test262 tests assume a clean environment per run. Running without this isolation will result in a number of failures already.

**Comment by anba** [comment]
Great! Then I'll remove those pesky `finally` blocks. :smile:

**Comment by anba** [comment]
Removed the `finally` blocks and replaced the commits.

**Pull request merged**
