### PR TITLE
Add `global` tests.

### PR DESCRIPTION
**Pull request by ljharb**
Closes #605, relates to #567 / https://github.com/tc39/proposal-global/issues/12 / https://github.com/bocoup/test262/commit/9c45e2ac684bae64614d8eb55789cae97323a7e7

### CODE REVIEW

**Comment by tcare** [comment]
Looks good

**Comment by ljharb** [comment]
@tcare this isn't stage 3 yet, but hopefully will be today or tomorrow. Please don't revert just yet; but please be prepared to do so after tomorrow if some new issue is found.

**Comment by leobalter** [comment]
oops, it's not stage 3 yet, but it might reach it tomorrow. Otherwise we'll need to revert it (again).

**Comment by leobalter** [comment]
Ok, I've answered before getting the comment from @ljharb, basically the same as I told.

**Comment by ljharb** [comment]
OK, this is now stage 3, so this is good to remain in master 🎉

**Pull request merged**
