### PR TITLE
tests for __proto__ and friends out of annex b

### PR DESCRIPTION
**Pull request by devsnek**
See https://github.com/tc39/ecma262/pull/2125

### CODE REVIEW

**Comment by ExE-Boss** [comment]
Normative optional features¹ should remain in the **annexB** subdirectory.

Only the `__proto__` property initialiser tests should be moved into the normative required directory.

---

¹ The `%Object.prototype.__proto__%` accessor, `%Object.prototype.__defineGetter__%`, `%Object.prototype.__defineSetter__%`, `%Object.prototype.__lookupGetter__%` and `%Object.prototype.__lookupSetter__%`.

**Comment by devsnek** [comment]
I will be giving them feature flags. They aren't part of annex B so they don't belong in that directory.

**Comment by devsnek** [comment]
i do believe this is ready

**Comment by ljharb** [comment]
linking to https://github.com/tc39/ecma262/pull/2125 (PR titles don't autolink)

**Comment by devsnek** [comment]
what needs to happen for this to be merged?

**Comment by devsnek** [comment]
@rwaldron ^

**Pull request merged**
