### PR TITLE
Add and update tests for Array.prototype iterator methods.

### PR DESCRIPTION
**Pull request by leobalter**
- Array.prototype.keys
- Array.prototype.entries
- Array.prototype.values

Some tests omitted for Array.prototype.values to avoid duplication with #377, they're properly covered there.

### CODE REVIEW

**Comment by ianwjhalliday** [comment]
LGTM

**Comment by bterlson** [comment]
:eggplant:

**Comment by leobalter** [comment]
There's no fixup commit to squash on this branch. Unless you prefer to squash the commits for keys, entries and values.

**Comment by bterlson** [comment]
Whoops! Nope, this one is fine. Thanks Leo!

**Comment by leobalter** [comment]
Thank you! :+1:

**Pull request merged**
