### PR TITLE
[WIP] Remove es6id and/org es5id if esid is present

### PR DESCRIPTION
**Pull request by leobalter**
Time to clean this up

### CODE REVIEW

**Comment by leobalter** [comment]
This modified some files replacing special EOL characters. I'm fixing it

**Comment by leobalter** [comment]
Closing this PR as it's still hard to fix all the files my editor changed by mistake

**Comment by leobalter** [comment]
I rebased this restricting the change only to generated files, this is good to eventually affect new generated files without problems

**Comment by ljharb** [comment]
(replaced by #2269)

**Comment by leobalter** [comment]
yes, GitHub saw the forced pushed branch and I couldn't reopen it.

**Pull request closed without merging**
