### PR TITLE
Contributing: updates the Test Case Names section. Closes gh-150

### PR DESCRIPTION
**Pull request by rwaldron**
Initial draft of test case naming re-write

### CODE REVIEW

**Comment by smikes** [comment]
Also closes #136, which dropped off my radar.

**Comment by rwaldron** [comment]
I missed that, but will update the commit message to include it.

**Comment by rwaldron** [comment]
Updated. @bterlson if this is good to go, I will land

**Comment by bterlson** [comment]
Good to go, thanks! I'd press the merge button now but it sounds like you'd like to do that ;)

**Pull request merged**
