### PR TITLE
Update contribution guidelines

### PR DESCRIPTION
**Pull request by jugglinmike**
@bterlson It looks like the project's CONTRIBUTING.md file has fallen out of
date. I've tried to bring it in line with current expectations, though a number
of edits are more subjective than that (mostly relating to streamlining content
for new contributors). I'm submitting as a number of fine-grained commits, but
I'd be happy to squash prior to landing.

### CODE REVIEW

**Comment by jugglinmike** [comment]
@bterlson Do you want to include any code style preferences here? I'm thinking of line length in particular. Something like,

> **Code style**
> Except when the behavior under test mandates otherwise, please adhere to the following code style conventions:
> - Limit line length to 80 characters

etc.

**Comment by bterlson** [comment]
This is really good. I want to pull this in now after squash :)

I don't like 80 char line width. Are there other coding styles you might want to enforce? IMO we can cover this in a second PR. This content is too good to gate on that!

**Comment by jugglinmike** [comment]
@bterlson Sure; I've opened gh-297 to discuss coding style separately. As for squashing: would you prefer to land this as the individual non-fixup commits or as a single commit (containing all the non-fixup commit messages)?

**Comment by bterlson** [comment]
One commit is fine IMO.

**Comment by jugglinmike** [comment]
@bterlson great--this should be all set now

**Pull request merged**
