### PR TITLE
add fractionalSecondDigits.js for formatRange

### PR DESCRIPTION
**Pull request by FrankYFTang**

### CODE REVIEW

**Comment by FrankYFTang** [comment]
@sffc @leobalter @fabalbon

**Comment by sffc** [comment]
Good, but can you also add some more examples that:

1. Include year/month/day in addition to the seconds
2. Test some of the edge cases like what happens when fractionalSecondDigits is the only field selected

**Comment by sffc** [comment]
@Ms2ger

**Comment by leobalter** [comment]
It's also interesting to add fractionDigits containing 0s...

```
new Date(2019, 7, 10,  1, 2, 13, 000);
new Date(2019, 7, 10,  1, 2, 13, 001);
new Date(2019, 7, 10,  1, 2, 13, 100);
new Date(2019, 7, 10,  1, 2, 13, 010);
```

and asserting them from 1 to 3 digits.

**Comment by leobalter** [comment]
I'll work on a follow up for [mine](https://github.com/tc39/test262/pull/2242#issuecomment-511939403) and @sffc's [feedback](https://github.com/tc39/test262/pull/2242#issuecomment-511935705)

**Comment by Ms2ger** [comment]
> ```js
> new Date(2019, 7, 10,  1, 2, 13, 010);
> ```

Please be careful with octal notation when you write the follow up.

**Pull request merged**
