### PR TITLE
fix namespace set test

### PR DESCRIPTION
**Pull request by devsnek**

### CODE REVIEW

**Comment by leobalter** [comment]
The error from JSC is interesting. cc @rkirsling

**Comment by shvaikalesh** [comment]
It seems like [recent JSC change](https://trac.webkit.org/changeset/259676/webkit) makes `test262-harness` fail initialization strict mode, https://test262.report results by merely a half.
`test262/Runner.pm` is unaffected.

**Comment by leobalter** [comment]
all the tests captured here are not using the WebKit's Runner.pm but test262-harness. One should not affect the other for sure.

I don't have access to test262.report's code but it seems like something @rwaldron could get fixed or adjusted.

**Comment by shvaikalesh** [comment]
A stack trace from `test262-harness`:

```
$ test262-harness --hostType=jsc --hostPath='WebKitBuild/Debug/jsc' JSTests/test262/test/harness/dateConstants.js
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.relative (path.js:1163:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/test262-harness/bin/run.js:143:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by rkirsling** [comment]
@shvaikalesh I think that one is just because there's legitimately no `test262Dir` (it's just the error from `path.relative(process.cwd(), null)`).

With local clones of test262 and test262-harness:
```
λ DYLD_FRAMEWORK_PATH=WebKitBuild/Release node ../test262-harness/bin/run.js --hostType=jsc --hostPath=WebKitBuild/Release/jsc ../test262/test/harness/dateConstants.js
FAIL ../test262/test/harness/dateConstants.js (strict mode)
  Expected no error, got TypeError: Attempted to assign to readonly property.

Ran 2 tests
1 passed
1 failed
```

**Comment by shvaikalesh** [comment]
Thank you @rkirsling.

With great help of `--saveCompiledTests` CLI parameter, I tracked the `TypeError` down to

```js
$262.IsHTMLDDA = function() {};
```

line, which legitimately fails because `"IsHTMLDDA"` property has no setter.
This regression was introduced in [r259587](https://trac.webkit.org/changeset/259587/webkit), now being fixed in [webkit.org/b/210470](https://bugs.webkit.org/show_bug.cgi?id=210470).

Also, since `$262.IsHTMLDDA` is properly implemented in JSC, it can be removed from `eshost`: https://github.com/bterlson/eshost/pull/105.

**Pull request merged**
