### PR TITLE
Update RegExp.prototype.{match,replace} tests to expect Get(rx, "flags")

### PR DESCRIPTION
**Pull request by gibson042**
This adds tests for https://github.com/tc39/ecma262/pull/2791 , which reached consensus at the July 2022 TC39 meeting.

### CODE REVIEW

**Comment by gibson042** [comment]
This results in failures, as expected:
<details><summary>results</summary>

```
FAIL test/built-ins/RegExp/prototype/Symbol.match/flags-tostring-error.js (default)
  Expected a CustomError but got a Test262Error

FAIL test/built-ins/RegExp/prototype/Symbol.match/get-flags-err.js (default)
  Expected a CustomError but got a Test262Error

FAIL test/built-ins/RegExp/prototype/Symbol.match/get-unicode-error.js (default)
  Expected a Test262Error to be thrown but no exception was thrown at all

FAIL test/built-ins/RegExp/prototype/Symbol.replace/flags-tostring-error.js (default)
  Expected a CustomError but got a Test262Error

FAIL test/built-ins/RegExp/prototype/Symbol.replace/get-flags-err.js (default)
  Expected a CustomError but got a Test262Error

FAIL test/built-ins/RegExp/prototype/Symbol.replace/get-unicode-error.js (default)
  Expected a Test262Error to be thrown but no exception was thrown at all
```
</details>

Do we have instructions for how to test such changes by modifying engine262?

**Comment by ptomato** [comment]
We don't have those instructions yet. That would be a great tutorial to have!

**Review by mathiasbynens — APPROVED** [review]

**Comment by gibson042** [comment]
@ptomato Do you have such experience? I don't, but I'd be happy to write something up from either a past example or a new pairing session.

**Comment by ptomato** [comment]
I don't either, and would love to learn. IIRC @devsnek once gave a demonstration of implementing a small proposal in engine262, so maybe they could help?

**Comment by devsnek** [comment]
@gibson042 maybe drop by https://matrix.to/#/#engine262:matrix.org and we can discuss? this should hopefully be quite straight-forward but i'd love to hear your feedback on the process.

**Review by ljharb — APPROVED** [review]
LGTM

**Comment by gibson042** [comment]
With help from @devsnek, I was able to verify that engine262 modifications to implement https://github.com/tc39/ecma262/pull/2791 result in it passing all tests broken by this PR. :tada:

**Review by ljharb — APPROVED** [review]

**Pull request merged**
