### PR TITLE
Update the test based on v35 of UTS35

### PR DESCRIPTION
**Pull request by FrankYFTang**
see http://unicode.org/reports/tr35/#LocaleId_Canonicalization
@anba

### CODE REVIEW

**Comment by FrankYFTang** [comment]
@Ms2ger @gibson042

**Comment by Ms2ger** [comment]
@ryzokuken

**Comment by rwaldron** [comment]
Kindly summoning @anba @gibson042 @ryzokuken

**Comment by FrankYFTang** [comment]
ping

**Comment by FrankYFTang** [comment]
@zbraniecki @anba please help to review

**Review by zbraniecki — APPROVED** [review]

**Comment by FrankYFTang** [comment]
@mathiasbynens

**Review by mathiasbynens — APPROVED** [review]

**Comment by rwaldron** [comment]
Thanks everyone

**Pull request merged**
