### PR TITLE
Unify indentation in test_monkeyYaml.py

### PR DESCRIPTION
**Pull request by arv**

### CODE REVIEW

**Comment by arv** [comment]
@smikes @bterlson

**Comment by jugglinmike** [comment]
This bothered you all weekend, didn't it? :P

**Comment by arv** [comment]
Kind of but I told myself not to touch it until I got into work...

**Comment by bterlson** [comment]
Personally I enjoy test262 reviews over my Sunday morning coffee ;)

**Comment by smikes** [comment]
Thanks! :100:

**Pull request merged**
