### PR TITLE
Destructuring Binding - syntax and simple initialization

### PR DESCRIPTION
**Pull request by leobalter**
I believe at least the minimal tests for syntax is ready, but there's a lot of other tests to bring to this PR.

Possibly coming up next week:

- [ ] complete tests for ObjectBindingPattern initilization (13.3.3.5)
- [ ] ArrayBindingPattern initialization (IteratorBindingInitialization 13.3.3.6)
- [ ] KeyedBindingInitialization (13.3.3.7)
- [ ] BindingPattern statements
- [ ] Function length based on parameters list (13.3.3.4)

Extra, maybe not necessary for this coverage goal:

- [ ] check tests for BoundNames
- [ ] destructuring binding on variable declarations
- [ ] ForDeclaration/ForBinding 
- [ ] CatchParameter

### CODE REVIEW

**Comment by leobalter** [comment]
I'm gonna stop this PR from where it is and wait for #467. 

This PR only covers the syntax for Destructuring Binding on function parameters, it's missing coverage for other forms as statements, variable declarations, for, catch, etc. which might produce a lot of repetitive code which is way easier to target after #467 is solved.

The initialization tests should also consider this repetitive syntax work.

Said that, I believe we can stick with the current tests as an introductory phase, even as a parameter to support on the other syntax forms.

**Comment by goyakin** [comment]
@leobalter, these tests look good to me. If you want, I can merge them in now rather than waiting for #467. We can refactor the tests later.

**Comment by leobalter** [comment]
@goyakin Thanks! I agree it's good to merge now and refactor later.

**Comment by leobalter** [comment]
Thanks!

**Pull request merged**
