### PR TITLE
Console Runner: Revert Parallelization and Formally Deprecate

### PR DESCRIPTION
**Pull request by jugglinmike**
I've heard it mentioned that the Python "console runner" utility is deprecated,
but there is no documentation in this project to suggest this. If it is the
case, we should be more clear about it in order to better set expectations for
consumers and contributors.

A decision to deprecate would also motivate the removal of a recent feature
addition to the console runner--support for parallelization. To date, three
bugs have been found in that implementation. As an optimization to a deprecated
tool, the maintenance overhead is not justified.

Resolves gh-512.

### CODE REVIEW

**Comment by goyakin** [comment]
We at Microsoft don't use the Python runner. If nobody is actually is using it, I'd be in favor of **officially** deprecating it instead of [fixing the race condition](https://github.com/tc39/test262/pull/514).

**Comment by tschneidereit** [comment]
Clearly I'm not smart enough to write multithreaded code :(

Still, the console runner being the only way to properly automate running these tests in a shell (and thus with reasonable speed), I'm opposed to deprecating it. I would in fact like to use it to run test262 in our pre-commit tests.

If people are strongly opposed to having a console runner, then I'll just import what I need into our repository and only use test262 as the source of tests. I'd find that unfortunate, though.

**Comment by jugglinmike** [comment]
I think that offering a console runner has always been an over-extension of this project's responsibilities. We can't serve everyone, so some consumers will invariably build their own runner anyway.

So while I understand your desire to have an executable packaged with Test262, it seems healthier in the long run to place that responsibility elsewhere. As you mention, you are free to maintain a customized copy of the runner in your project. In that case, you'll be happy to know that we're formalizing the expectations for test interpretation--see gh-508.

You may not want to take on that burden, though. As luck would have it, @bterlson has built [test262-harness](https://github.com/bterlson/test262-harness) an excellent replacement using Node.js--maybe that will suit your needs?

**Comment by tschneidereit** [comment]
Ok, I can't say I agree or fully understand why hosting a runner isn't a
useful part of this project, but as you say I can just fork and maintain a
copy.


> You may not want to take on that burden, though. As luck would have it,
> @bterlson <https://github.com/bterlson> has built test262-harness
> <https://github.com/bterlson/test262-harness> an excellent replacement
> using Node.js--maybe that will suit your needs?
>

Thanks for the pointer. Doesn't help me though, because our buildsystem
doesn't have node.js where I'd need it.

**Comment by littledan** [comment]
Before officially deprecating this tool being part of test262, let's consult Apple to see if they use it or plan to use it. If two browsers find it useful, then it would make sense to stay. If it's just for one, then we might consider deprecating it.

I think it's within scope of this project to make sure it's usable. It comes down to details whether this test runner being maintained as part of this project is important, rather than any abstract principle, I think.

**Comment by kmiller68** [comment]
We don't have any current plans to use the Python test runner. I'll be integrating test262 into our existing infrastructure to make running tests simpler. That said, if the console running is being actively maintained I don't see any reason to deprecate or remove it from the project.

**Comment by littledan** [comment]
I don't really see the point in leaving something in the repository frozen and deprecated. Why don't we either let Till maintain it here for Mozilla's use, or remove it?

**Comment by tschneidereit** [comment]
>
> I don't really see the point in leaving something in the repository frozen
> and deprecated. Why don't we either let Till maintain it here for Mozilla's
> use, or remove it?
>

I'd be ok with either. One thing to note might be that people do seem to
use it, otherwise the issues I introduced wouldn't have mattered, right?

**Comment by jugglinmike** [comment]
TC-39 agreed to deprecate the runner in 2014. This decision wasn't
well-communicated, so there was some contention a few months later when
@domenic filed gh-128 to remove the runner. The discussion died off without a
change to TC-39's decision or to the runner itself.

I came across the bugs when implementing new features for the test runner:
first for the proposed `async` flag, and later for executing module code. I
suggested formal deprecation in light of the long-standing TC-39 decision and
because I was afraid I was devoting energy to a rarely-used/updated tool.

**Comment by littledan** [comment]
Thanks for the reference to the history. Let's bring this up at the next TC39 meeting to see if we should reverse the deprecation decision. To address the concern about wasted maintanence work: Whether or not the runner is deprecated, I don't think @jugglinmike is personally responsible for maintaining it. But it would definitely be unfortunate if Mozilla and V8 (for the inner parts Andreas mentioned) needed to maintain separate copies of the same code.

**Pull request merged**
