### PR TITLE
Add basic Symbol constructor tests

### PR DESCRIPTION
**Pull request by shvaikalesh**
Older V8s used to have wrong `Symbol.length` [bug tracker](https://bugs.chromium.org/p/v8/issues/detail?id=4882)

### CODE REVIEW

**Comment by leobalter** [comment]
how did we miss this coverage?

Thanks for the tests! LGTM.

**Comment by leobalter** [comment]
@shvaikalesh we could use the new `verifyProperty` helper, are you interested in sending a new PR with this change? 

I'm merging this for now as the tests are fine and valid.

**Comment by shvaikalesh** [comment]
@leobalter When https://github.com/tc39/test262/pull/1067 lands, I can make a PR utilizing `verifyProperty` in the whole test base if it is desirable.

**Comment by leobalter** [comment]
I can't describe how amazing this would be :)

**Pull request merged**
