### PR TITLE
Sync to PR701

### PR DESCRIPTION
**Pull request by FrankYFTang**
In TC39 2022-07-20, we decide to merge PR701. 
See https://github.com/tc39/ecma402/pull/701 and https://docs.google.com/presentation/d/1UUvbf3FFu9PGtrPAKPdMad9DZuVFLIvkAsAxyJZyvxM/edit 
for details.

### CODE REVIEW

**Comment by FrankYFTang** [comment]
@ryzokuken @gibson042 @romulocintra @sffc

**Review by ryzokuken — DISMISSED** [review]

**Review by gibson042 — APPROVED** [review]

**Comment by sffc** [comment]
Wouldn't it be better if we made the tests expect that the format functions don't throw and produce some kind of output, rather than just delete them?

**Comment by ptomato** [comment]
Agreed, it'd be nice to have some sort of affirmative test that the reverse order works; otherwise implementations that don't update still pass the tests.

**Comment by FrankYFTang** [comment]
tests added. PTAL

**Review by sffc — APPROVED** [review]

**Review by ptomato — APPROVED** [review]

**Pull request merged**
