### PR TITLE
Object computed property is an ES6 feature.

### PR DESCRIPTION
**Pull request by nadavrot**
@sebmarkbage

### CODE REVIEW

**Comment by tcare** [comment]
It may be an ES6 feature, but we should leave an esid in so that it maps to future spec changes regardless of the numbering.

**Comment by nadavrot** [comment]
@tcare I am not sure I understand. The test case is not a valid ES5 program. Why do we want to mark it as esid and not es6id? Is it because of the label that follows?

**Comment by leobalter** [comment]
esid is not meant for es5. For es5 features we used es5id, than we set es6id for es6. The problem is that it became unsustainable and unnecessary after the standards moved to GitHub and TC39 is using the per year releases model.

esid just means this is related to the last version of the specs (draft included). Test262 does not keep track of per specific editions of the specs. There's just one, new editions replace the previous.

In this PR esid could be kept, as it's a better mapping for the particular feature. You can still add the es6id if you want, it's not relevant and not necessary. These tags are just mappings of the features in the specs, not the version of the specs.

**Comment by rwaldron** [comment]
@nadavrot ping

re: @leobalter's question: 

> In this PR esid could be kept, as it's a better mapping for the particular feature. You can still add the es6id if you want, it's not relevant and not necessary.

Can this be closed or are you going to make that change above?

**Comment by nadavrot** [comment]
Thanks for the help guys. Closing.

**Pull request closed without merging**
