### PR TITLE
Update test for distinct NaN replacement on DefineOwnProperty

### PR DESCRIPTION
**Pull request by leobalter**
Closes gh-683
Ref gh-648
Ref tc39/ecma262#353

@jugglinmike @bakkot, would you review this one, please?

### CODE REVIEW

**Comment by bakkot** [comment]
Looks good to me.

**Comment by jugglinmike** [comment]
There is a typo in the commit message. It should reference issue 353 on the
ECMA262 issue tracker, not issue 343.

https://github.com/tc39/ecma262/pull/353 

Otherwise this looks good to me!

**Comment by leobalter** [comment]
Forced pushed with only the typo fix

**Comment by jugglinmike** [comment]
Merged to `master` at commit 3868f8f76580a229aa0ffdeeeafe091a7ca3e087. This was a tricky one!

**Pull request closed without merging**
