### PR TITLE
harness: add checks of descriptor attributes

### PR DESCRIPTION
**Pull request by smikes**
First check if descriptor is set up correctly, then actually
verify that the attribute (writability, enumerability,
configurability) is as expected.

### CODE REVIEW

**Comment by smikes** [comment]
This fixes #170.

Verified using io.js 1.2 that `../test262-harness/bin/run.js test/built-ins/Object/defineProperty/*.js -r node-ip` before/after this change had the same success/failures.

**Comment by bterlson** [comment]
Well that was fast! Thanks!

**Comment by smikes** [comment]
Wednesday is my work day.  For another 1.5 hours... got any requests?

**Comment by bterlson** [comment]
Wish I knew the sum total of V8's contributions, would be nice to start filing any expected gaps :)

Symbol.species might be a good target? Now that I know Wednesday is your work day I can collect stuff for you to do throughout the week ;)

**Comment by smikes** [comment]
I will look at Symbol.species.  ES6 is huge!

**Pull request merged**
