### PR TITLE
Fix import assertions tests

### PR DESCRIPTION
**Pull request by anba**
- Correct file paths in "ensure-linking-error_FIXTURE.js"
- Remove no longer valid assertion in "import-assertion-empty.js".

See also #3919.

### CODE REVIEW

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
@anba Not sure if you saw it, but if you need `with` tests you can find them at https://github.com/tc39/test262/pull/3921 (I will apply this patch also to that PR).

**Comment by anba** [comment]
> @anba Not sure if you saw it, but if you need `with` tests you can find them at #3921 (I will apply this patch also to that PR).

I don't actually work on implementing import assertions, I only noticed these test failures when updating SpiderMonkey's test262 copy. :smile:

**Comment by ptomato** [comment]
Unfortunately, the auto-merge won't work because of #3891.

**Review by ptomato — APPROVED** [review]
Re-approving

**Pull request merged**
