### PR TITLE
replace Test262Error with $ERROR when possible

### PR DESCRIPTION
**Pull request by Meir017**

### CODE REVIEW

**Comment by leobalter** [comment]
This is going the opposite path we want for Test262. Ideally the recommended form is throwing a new Test262Error rather than using $ERROR directly. 

The current `$ERROR` usage is within legacy code we'd like to change in the future.

**Comment by leobalter** [comment]
I'd be fine to reopen this if we want to try the opposite approach. For now, I hope we don't go through this current proposed change.

**Comment by rwaldron** [comment]
I was also going to add that this is clearly marked as **DEPRECATED** in https://github.com/tc39/test262/blob/master/CONTRIBUTING.md

**Comment by leobalter** [comment]
To make things clear: #2668 was accepted due to the target test being legacy. The whole test needs improvement but the change just seemed better than the original usage (`$ERROR` is still better than `throw e` in a legacy test).

**Pull request closed without merging**
