### PR TITLE
Byte values harness

### PR DESCRIPTION
**Pull request by leobalter**

### CODE REVIEW

**Comment by leobalter** [comment]
it needs some fixes.... too early

**Comment by jugglinmike** [comment]
This looks good to me; just one thing: could you add the project's licensing boilerplate to the top of the new `harness/byteConversionValues.js` file?

**Comment by leobalter** [comment]
done!

**Comment by jugglinmike** [comment]
Thanks!

**Comment by jugglinmike** [comment]
Squashed and merged to `master` at commit bc42c6ab5ca34eed9f219c2a19d044217838d390

**Pull request closed without merging**
