### PR TITLE
Fix expected order of properties

### PR DESCRIPTION
**Pull request by devsnek**
its a four-way split so might as well just make it match the spec

```
┌────────────────┬───────────────────────────────┐
│ ChakraCore     │ 1,2,prototype,name,a,c,length │
├────────────────┼───────────────────────────────┤
│ engine262      │ 1,2,length,prototype,name,a,c │
│ engine262+     │                               │
├────────────────┼───────────────────────────────┤
│ JavaScriptCore │ 1,2,length,name,prototype,a,c │
│ QuickJS        │                               │
│ XS             │                               │
├────────────────┼───────────────────────────────┤
│ SpiderMonkey   │ 1,2,prototype,a,c,length,name │
├────────────────┼───────────────────────────────┤
│ V8             │ 1,2,length,prototype,a,c,name │
└────────────────┴───────────────────────────────┘
```

### CODE REVIEW

**Comment by ljharb** [comment]
Which one matches the spec? (or are they all permitted)

**Comment by devsnek** [comment]
only engine262 matches. everything else is wrong.

**Comment by ljharb** [comment]
Does this PR enforce the spec?

**Comment by devsnek** [comment]
@ljharb it updates the order to match the spec. currently, jsc/qjs/xs do not match the spec but they pass these tests.

**Comment by anba** [comment]
The current order should match <https://github.com/tc39/ecma262/pull/1490>. Also see <https://github.com/tc39/test262/pull/2299>.

**Comment by devsnek** [comment]
neat.

**Pull request closed without merging**
