### PR TITLE
`Promise.prototype.finally` thunks have a length of 0

### PR DESCRIPTION
**Pull request by ljharb**
Followup to #2471.

Thunks have a length of zero, since they take no arguments.

cc @devsnek @shvaikalesh

### CODE REVIEW

**Comment by shvaikalesh** [comment]
Let's also remove

> The "length" property of a Catch Finally function is 1.

and 

> The "length" property of a Then Finally function is 1.

from `info` sections, since they don't refer to thunks.

**Comment by ljharb** [comment]
Those are correct and must remain; they refer to the overarching functions described in https://tc39.es/ecma262/#sec-thenfinallyfunctions and https://tc39.es/ecma262/#sec-catchfinallyfunctions - not the thunks described in step 8 of either algorithm.

**Comment by devsnek** [comment]
I think this is actually a bit more complex:

```js
Promise.reject(new Error('owo'))
  .finally(function() {})
  .then(() => {}, () => {});

const { then } = Promise.prototype;
Promise.prototype.then = function(f) {
  print(`"${f.name}"`, f.length);
  return then.call(this, f);
};
```

```
┌────────────────┬───────────────┐
│ ChakraCore     │ "undefined" 0 │
│                │ "" 1          │
├────────────────┼───────────────┤
│ engine262      │ "" 0          │
│ GraalJS        │ "" 1          │
│ SpiderMonkey   │               │
│ V8             │               │
│ XS             │               │
├────────────────┼───────────────┤
│ JavaScriptCore │ "thrower" 0   │
│                │ "resolve" 1   │
├────────────────┼───────────────┤
│ QuickJS        │ "" 1          │
│                │ "" 1          │
└────────────────┴───────────────┘
```

The cell with v8 and spidermonkey is correct. First this is called with the 0-length thunk, then it is called again with a Promise Resolve Function (https://tc39.es/ecma262/#sec-promise-resolve-functions)

**Comment by rwaldron** [comment]
>  First this is called with the 0-length thunk, then it is called again with a Promise Resolve Function

@devsnek I think we should add a `calls` counter inside of `then` and make the appropriate assertions based on which call we're presently at

**Comment by ljharb** [comment]
ah, gotcha. i'll update this today to do that.

**Comment by ljharb** [comment]
@rwaldron updated; lmk what you think

**Pull request merged**
