### PR TITLE
Refactor, reorganize, and extend tests for line terminators

### PR DESCRIPTION
**Pull request by jugglinmike**
Many of the tests for the parsing of line terminators were expressed using eval. This made the tests more complex than necessary and also prevented the tests from providing value to ECMAScript parsers. Remove the use of eval and instead express the expectations with literal source text.

Some concerns were tested redundantly with multiple files. Remove the excess tests since they do not improve coverage.

Add new tests for concerns which were not previously covered.

This is another patch in service of gh-1356. These tests were particularly disorganized, so I've tried to make my process as clear as possible by spreading it across multiple commits. As another way to summarize, here's a comparison of file names in the `test/language/line-terminators` directory:

```diff
@@ -1,43 +1,33 @@
-7.3-10.js
 7.3-15.js
-7.3-1.js
-7.3-2.js
-7.3-3.js
-7.3-4.js
 7.3-5.js
 7.3-6.js
-7.3-7.js
-7.3-8.js
-7.3-9.js
-S7.3_A1.1_T1.js
-S7.3_A1.1_T2.js
-S7.3_A1.2_T1.js
-S7.3_A1.2_T2.js
-S7.3_A1.3.js
-S7.3_A1.4.js
-S7.3_A2.1_T1.js
+between-tokens-cr.js
+between-tokens-lf.js
+between-tokens-ls.js
+between-tokens-ps.js
+comment-multi-cr.js
+comment-multi-lf.js
+comment-multi-ls.js
+comment-multi-ps.js
+comment-single-cr.js
+comment-single-lf.js
+comment-single-ls.js
+comment-single-ps.js
+invalid-comment-single-cr.js
+invalid-comment-single-lf.js
+invalid-comment-single-ls.js
+invalid-comment-single-ps.js
+invalid-regexp-cr.js
+invalid-regexp-lf.js
+invalid-regexp-ls.js
+invalid-regexp-ps.js
+invalid-string-cr.js
+invalid-string-lf.js
+invalid-string-ls.js
+invalid-string-ps.js
 S7.3_A2.1_T2.js
-S7.3_A2.2_T1.js
 S7.3_A2.2_T2.js
-S7.3_A3.1_T1.js
-S7.3_A3.1_T2.js
-S7.3_A3.1_T3.js
 S7.3_A3.2_T1.js
-S7.3_A3.2_T2.js
-S7.3_A3.2_T3.js
-S7.3_A3.3_T1.js
-S7.3_A3.3_T2.js
-S7.3_A3.4_T1.js
-S7.3_A3.4_T2.js
-S7.3_A4_T1.js
-S7.3_A4_T2.js
-S7.3_A4_T3.js
-S7.3_A4_T4.js
-S7.3_A5.1_T1.js
-S7.3_A5.1_T2.js
-S7.3_A5.2_T1.js
-S7.3_A5.2_T2.js
-S7.3_A5.3.js
 S7.3_A5.4.js
 S7.3_A6_T1.js
 S7.3_A6_T2.js
```

### CODE REVIEW

**Comment by leobalter** [comment]
Thanks for the detailed work.

**Comment by adrianheine** [comment]
I think LS and PS are allowed in string literals according to [sec-line-terminators](https://tc39.github.io/ecma262/#sec-line-terminators):

> A line terminator cannot occur within any token except a StringLiteral, Template, or TemplateSubstitutionTail. \<LF> and \<CR> line terminators cannot occur within a StringLiteral token except as part of a LineContinuation.

**Comment by mathiasbynens** [comment]
Yep, these two tests should be removed:

- https://github.com/tc39/test262/blob/4f1155c566a222238fd86f179c6635ecb4c289bb/test/language/line-terminators/invalid-string-ls.js
- https://github.com/tc39/test262/blob/4f1155c566a222238fd86f179c6635ecb4c289bb/test/language/line-terminators/invalid-string-ps.js

As @adrianheine points out, this change has already made it into the spec draft. The proposal was https://github.com/tc39/proposal-json-superset.

**Comment by mathiasbynens** [comment]
PR: https://github.com/tc39/test262/pull/2044

**Pull request merged**
