### PR TITLE
Tests for NumericSeparatorLiteral. 

### LINKED ISSUE #1051: Add tests for numeric separator
Once the spec grammar is written, reference: https://github.com/samuelgoto/proposal-numeric-separator

### PR DESCRIPTION
**Pull request by leobalter**
Closes #1051
Reverts #1188
Restores #1176

### CODE REVIEW

**Comment by leobalter** [comment]
Cleaning up my own mess.

**Comment by leobalter** [comment]
This ready to land label means the PR contents are reviewed. It still needs to await for stage 3.

**Comment by littledan** [comment]
Are there any tests here on the behavior of functions like Number and parseFloat for invalid uses of _, e.g., at the beginning or end of a string?

**Comment by rwaldron** [comment]
Rebased

**Comment by rwaldron** [comment]
Rebased

**Comment by anba** [comment]
There are various tests for the `Number` constructor and numeric separators, but the proposal does not (or no longer?) extend `Number` to support numeric separators. It'd be nice to update the test, so we can use them to verify https://bugzilla.mozilla.org/show_bug.cgi?id=1421400 is correctly implemented.

**Comment by rwaldron** [comment]
> but the proposal does not (or no longer?) extend Number to support numeric separators

@anba an oversight, I will address this as soon as I can. Thanks for the report.

**Comment by adrianheine** [comment]
btw, numeric separators [is stage3](https://github.com/tc39/proposals/commit/6e218773d0d78e7e6a62a9bf3f658af2f5a0aefa).

**Comment by littledan** [comment]
@rwaldron It might be good to take a look at https://github.com/tc39/proposal-numeric-separator/issues/25 (as well as https://github.com/tc39/proposal-numeric-separator/issues/32) before removing these tests.

**Comment by leobalter** [comment]
@anba I fixed the tests to match the current specs. 

I still need to write something for escape sequences... tc39/proposal-numeric-separator#25

**Pull request merged**
