### PR TITLE
Add link to web-based runner

### PR DESCRIPTION
**Pull request by bakkot**
Page is [here](https://bakkot.github.io/test262-web-runner/), source is [here](https://github.com/bakkot/test262-web-runner).

This project is incidentally the origin of my recent handful of fixes.

### CODE REVIEW

**Comment by littledan** [comment]
Have you tried this on various browsers? Does it run well to completion across browsers, or do you ever encounter issues with that?

**Comment by bakkot** [comment]
Works fine on Safari and Chrome, although crashes on sufficiently old Safari. Firefox appears to hang on some of the Array.prototype.slice/splice tests (at a guess it's trying to allocate massive amounts of memory) but is otherwise fine. Don't have a copy of IE or Edge around for easy testing.

**Comment by bakkot** [comment]
Also, results on Chrome pretty much look [as expected](https://github.com/v8/v8/blob/master/test/test262/test262.status), though I haven't verified every single result. I don't know of similar places to look for what to expect of other browsers.

--

I should also mention that the UI is a bit less smooth on Chrome (lagging by a few seconds while running tests instead of continuously updating) than FF or Safari, but all my attempts to fix it made it take twice as long to finish on Chrome. Didn't seem worth it.

**Comment by hzoo** [comment]
This is awesome @bakkot! Was going to try running Babel with https://github.com/bterlson/test262-harness but this is cool too

**Pull request merged**
