### PR TITLE
re-enable graaljs

### PR DESCRIPTION
**Pull request by devsnek**
Closes https://github.com/tc39/test262/issues/3703

### CODE REVIEW

**Review by ptomato — APPROVED** [review]
LGTM, in theory. How confident are you in practice that this fix is going to stick? The GraalJS installation process has been failing every so often for several months... so I'd prefer not have to keep removing and reinstating it.

**Comment by devsnek** [comment]
@ptomato i asked the same question of @woess who fixed this and they've said the new install process should fix the previous issues we saw.

**Comment by ptomato** [comment]
OK, works for me!

**Comment by ptomato** [comment]
@devsnek @woess Unfortunately that didn't last long: https://app.circleci.com/pipelines/github/tc39/test262/4582/workflows/5f805870-3878-4904-a327-22abb5d3c4ce/jobs/42830

Any ideas for quick fixes? Otherwise I'll plan to revert this.

**Comment by ptomato** [comment]
I missed earlier that we need to bump the esvu version to actually get this fix :face_with_spiral_eyes: 
See #3736

**Pull request merged**
