### PR TITLE
More fixes for bigint and MIN_VALUE comparisons

### PR DESCRIPTION
**Pull request by leobalter**
@anba this should end the issues with MIN_VALUE comparisons. The assertions are tricky to read, but I believe they are verified now.

### CODE REVIEW

**Comment by anba** [comment]
The changes look good to me!

https://github.com/tc39/test262/blob/2f655036d4f969d9afd8eb36e7baedfbcd66f373/test/language/expressions/less-than/bigint-and-number.js#L34-L35 needs to be updated, too.

**Comment by littledan** [comment]
I'm confused; why is this correct?

**Comment by anba** [comment]
> I'm confused; why is this correct?

`Number.MIN_VALUE` is 5 &times; 10<sup>-324</sup>, so it should be greater than `0n`, shouldn't it?

**Comment by littledan** [comment]
Oh sorry, of course, I was just confused about what Number.MIN_VALUE was.

**Pull request merged**
