### PR TITLE
test: private method usage: calling private method

### PR DESCRIPTION
**Pull request by jbhoosreddy**
Tracking issue: #1343 

Summary of changes:
1. Add test for private method usage

> `Calling a private method`

### CODE REVIEW

**Comment by jbhoosreddy** [comment]
@leobalter @rwaldron This one needs more work on both frontmatter and coverage. But I wanted to get some initial 👀 on it.

1. Can't find the normative spec text for the description in the spec.
2. Also should coverage include all variants of private methods?

**Comment by jbhoosreddy** [comment]
Also, wanted to use this space to discuss my next PR
> Reading a private method separately from calling it
>  + All instances of the class share the same function identity for the private method

Thoughts on testing function identity? I think I know it but just wanted to verify. cc @mkubilayk we can catch up about this tomorrow.

**Comment by rwaldron** [comment]
If these are just valid syntax tests then there shouldn't be any assertions (there may be older tests that do this, but those just need to be split into "syntax only" and "runtime semantics only"). If you want to do runtime semantics tests that exercise all of the grammar variants, then you'll need to use `src/class-elements/productions` (`template: productions`).

**Comment by leobalter** [comment]
I'm working on a fix for these cases.

The current cases are definitely not calling the presented assertions. They are also a simplified version of the rs-private-getter*.case / rs-private-method*.case files in the same folder.

**Comment by leobalter** [comment]
fixed on #1919

**Pull request closed without merging**
