### PR TITLE
switch to esvu to streamline engine installs

### PR DESCRIPTION
**Pull request by devsnek**
removes engine specific bin paths and gets rid of needing to build engine262 from scratch

### CODE REVIEW

**Comment by rwaldron** [comment]
@devsnek what's your support plan look like?

**Comment by devsnek** [comment]
@rwaldron i don't understand the question

**Comment by rwaldron** [comment]
@devsnek Sorry, I meant: what is your support plan for `esvu`? I was hoping to get an idea of what kind of maintenance reliability commitment can be guaranteed? I _really_ want to use it for the `quickjs-run-test262` support, so I think I'm ready to just take the risk.

**Comment by devsnek** [comment]
@rwaldron I'm planning to keep it updated and working for the foreseeable future. I'm not being compensated to make it so I don't want to guarantee anything but I should be able to deal with bugs fairly quickly.

**Pull request merged**
