### PR TITLE
Integration tests: Membrane (Proxy, WeakMap, Reflect, Map).

### PR DESCRIPTION
**Pull request by ajvincent**
See #1026 - this is a first set of integration tests.

A few trouble spots:

- I didn't pick out a specific esid for any of the tests.  It's a required field for the tests' frontmatter... but these are integration tests, so no single section of ECMAScript is being tested.  I suggest an "integration-tests(section, section, ...)" esid format, for clarity.
- In the [recommended test-262 web runner](https://bakkot.github.io/test262-web-runner/), I couldn't put the integration-Membrane.js file into a subdirectory of harness/ .  (This is also the only test runner I actually used to develop and run these tests.)
- This is, I believe, my first contribution to test-262, and of course it's in a new area entirely.  So it needs to be more carefully reviewed, for both design and correctness.  At TC39 in July 2018, it was suggested that test-262 might not be the right repository for integration tests, but this is just a starting point.

### CODE REVIEW

**Comment by ajvincent** [comment]
That's really odd:  I had a linting failure for the features part of the frontmatter, but when I fixed that, another automated test failed which had passed only a few minutes ago.

**Comment by leobalter** [comment]
I'd like to give these tests a proper space for many reasons.

For now I created https://github.com/tc39/test262-integration for them just like the test262-parser-tests project.

These tests have different requirements than the traditional unit tests from Test262 and we can have a better perspective of failure/passing reports if we can set them there. Also, the details for Test262 (this project) should not be a blocker for the new tests.

If they come as well as different projects, we could also improve timing when they are consumed. e.g. I could have a special CI job for these.

WDYT?

If you bring these tests there we can set goals to get these tests running on different targets and identify how to better get results and effects from this work.

**Comment by rwaldron** [comment]
@leobalter I think this is a brilliant idea—looking forward to seeing how that project evolves!

**Comment by littledan** [comment]
I think it's important that this project make it easy for JS implementations to integrate the tests. If it starts breaking into multiple repositories, with their own setups, that could be hard. Do we know how successful test262-parser-tests has been at getting integrated into JS engines?

**Comment by leobalter** [comment]
> Do we know how successful test262-parser-tests has been at getting integrated into JS engines?

I don't know. I didn't work on the engagement for engines to integrate these tests neither I can afford with time to maintain that project.

In other scope, I can find some plans for the integration tests and I'd like to fit more relaxed goals for the new project that wouldn't just fit into Test262 that we could rely on. Saying that, we can work on some integration and even CI jobs, e.g. webdriver to experiment outreach ourselves.

Multiple repositories is not a bad thing and git has nice tools to integrate things.

> with their own setups

Do we have all the necessary setup identified for these integration tests? Do we want or need more? Can we fit all of them on Test262?

We have a very similar plan for stress tests and this integration project might be the answer or just go as parallel.

If we identify all of these on the new project we can have all the answers before just pushing more content that won't be used at its best.

**Comment by ajvincent** [comment]
Honestly, I'm fine with whatever the consensus is... but I do need a framework to put the tests in.  I notice that test262-integration is a bare-bones repository having only two files in it, which is obviously insufficient.

I also don't mind being the guinea pig with these membrane-oriented tests as the starting point.  But my time is limited, particularly when my university classes are in session.  In short, I must fill a support role, not a lead one.

**Comment by littledan** [comment]
Would it make sense to share tests between JavaScript implementations in this integration test repo, or should that be a fourth place?

**Comment by littledan** [comment]
cc @gsathya

**Comment by ajvincent** [comment]
I think I can close out this pull request now, as test262-integration has the tests.

**Pull request closed without merging**
