### PR TITLE
built-ins/Array/*: make all indentation consistent (depth & character)

### PR DESCRIPTION
**Pull request by rwaldron**

### CODE REVIEW

**Comment by leobalter** [comment]
These changes are massive.

Trying to follow a minimum fair review process I'll at least run all the changed files locally and compare the results with the master branch for consistency.

The Function and Regexp folders will require some extra steps.

The language folder should go through a different and way more strict process as well.

**Comment by anba** [comment]
Some of the changes are still of doubtful value. Examples:

- seven concise lines:
https://github.com/tc39/test262/blob/2fb8eca677ea2c904ff706c86aaf9371435aaa2b/test/built-ins/Date/UTC/coercion-order.js#L20-L27
are blown up to fourty-three lines:
https://github.com/rwaldron/test262/blob/3deda6331d287a86d7f2580111b4730b1fedddee/test/built-ins/Date/UTC/coercion-order.js#L20-L62

- Intentional indentation is lost:
https://github.com/tc39/test262/blob/2fb8eca677ea2c904ff706c86aaf9371435aaa2b/test/built-ins/Atomics/isLockFree/value.js#L10-L13
https://github.com/rwaldron/test262/blob/9de36610c4b32eed662a4f3c2536b78045080acf/test/built-ins/Atomics/isLockFree/value.js#L10-L15

- Comments are no longer attached to the correct line:
https://github.com/tc39/test262/blob/2fb8eca677ea2c904ff706c86aaf9371435aaa2b/test/built-ins/Atomics/compareExchange/good-views.js#L20
https://github.com/rwaldron/test262/blob/9de36610c4b32eed662a4f3c2536b78045080acf/test/built-ins/Atomics/compareExchange/good-views.js#L25

**Comment by rwaldron** [comment]
@anba I'm trying to discard those kinds of changes as I encounter them—I appreciate your help in reviewing

**Comment by leobalter** [comment]
I'm waiting for the changes to be applied, @rwaldron. Please let me know when this is ready for another review

**Comment by leobalter** [comment]
they are actually ready.

**Pull request merged**
