### PR TITLE
Temporal: Regularize tests and expand coverage

### PR DESCRIPTION
**Pull request by ptomato**
Improvements to "calendar-case-insensitive" tests and some of the "calendar-temporal-object" tests. These refactors are in preparation for tests that I'm writing for upcoming normative changes.

### CODE REVIEW

**Review by Aditi-1400 — COMMENTED** [review]
Why did we need to unroll the calls to `TemporalHelpers.checkToTemporalCalendarFastPath()` ? 🤔

**Comment by ptomato** [comment]
Good question. It seemed like the best thing to do since I wanted to change it for some tests but not others. (I guess that was an indication that probably it was too specific for a Temporal helper in the first place.)

**Review by Aditi-1400 — APPROVED** [review]

**Comment by Aditi-1400** [comment]
Thanks! :)

**Comment by ptomato** [comment]
Could I get a maintainer stamp on this one, please?

**Review by Ms2ger — APPROVED** [review]

**Pull request merged**
