### PR TITLE
Increase coverage of String.prototype.replace $xy replacement patterns

### PR DESCRIPTION
**Pull request by gibson042**
* $xy is a valid capture index
* $xy is not a valid capture index but $x is
* neither $xy nor $x is a valid capture index

Ref https://github.com/tc39/ecma262/issues/1426
Ref https://github.com/tc39/ecma262/pull/3157

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
Confirmed these tests pass my ES2024 GetSubstitution implementation in `es-abstract`, and fail on <= ES2023 (as expected)

**Comment by ljharb** [comment]
update; https://github.com/tc39/ecma262/pull/3157#issuecomment-1734728798 should get some coverage too

**Comment by gibson042** [comment]
@ljharb coverage expanded

**Review by ljharb — APPROVED** [review]

**Comment by ptomato** [comment]
This normative change got consensus conditionally in the 2023-09 TC39 plenary meeting. "If there is a mismatch between engines, the presenter should bring the change back to TC39 to discuss next steps." So I guess before we land this, the proponents of the normative change should perform that investigation.

**Comment by gibson042** [comment]
Done. The only implementation with failures is engine262, which does not implement the single-digit fallback:
* `$10` is not a capture index (but `$1` is) in /(x)/
* `$10` is not a capture index (but `$1` is) in /(x)($^)?/
* `$10` before `0` is not a capture index (but `$1` is) in /(x)/
* `$10` before `0` is not a capture index (but `$1` is) in /(x)($^)?/
* `$20` is not a capture index (but `$2` is a failed capture index) in /(x)($^)?/
* `$20` is not a capture index (but `$2` is) in /((((((((((x))))))))))/
* `$20` before `0` is not a capture index (but `$2` is a failed capture index) in /(x)($^)?/
* `$20` before `0` is not a capture index (but `$2` is) in /((((((((((x))))))))))/

```sh
$ eshost -se '"foo-x-bar".replace(/(x)/, "|$10|")'
#### ChakraCore, GraalJS, Hermes, JavaScriptCore, Moddable XS, QuickJS, SpiderMonkey, V8
foo-|x0|-bar

#### engine262
foo-|$10|-bar
```

**Comment by ptomato** [comment]
Thanks. So does that mean there are no longer any blockers for this?

**Comment by gibson042** [comment]
Yes, that is my understanding.

**Comment by ljharb** [comment]
It's easy to squash it at landing time, but I wanted more reviews before landing it.

**Review by linusg — APPROVED** [review]
LGTM, also passes with my [literal implementation of `GetSubstitution`](https://codeberg.org/kiesel-js/kiesel/src/commit/76e0de0719cf14727ba9d574a68638d431dd4d87/src/builtins/string.zig#L87-L310).

**Pull request merged**
