### PR TITLE
tools: update lint.py to work with pip 10+ some more

### PR DESCRIPTION
**Pull request by Ms2ger**
main() and InstallRequirement were also removed from the public API.

### CODE REVIEW

**Comment by leobalter** [comment]
While this looks good to me, I'd like to get feedback from @jugglinmike.

**Comment by jugglinmike** [comment]
I'm not able to test this locally, but I trust @Ms2ger knows what's up.

Still, we ought to be testing the environments that we intend to support. That means extending the CI configuration to run these tests with pip 10 (likely as a follow-up, unless anyone involved can make quick work of it here).

**Comment by Ms2ger** [comment]
I'm not planning to try to set up CI for this at this time, so I'd prefer deferring that to a followup.

**Comment by leobalter** [comment]
Let's land this for now and we can quickly react to any further report if it causes an unexpected problems.

**Pull request merged**
