### PR TITLE
Fix `single-line-html-close-first-line-*` failing with `Test262Error is not defined`

### LINKED ISSUE #4020: Tests for `-->` in the first line should not have `raw` flag.
The following tests added in https://github.com/tc39/test262/pull/4002 have the `raw` flag but are expected to throw a `Test262Error`:
```
test/annexB/language/comments/single-line-html-close-first-line-1.js
test/annexB/language/comments/single-line-html-close-first-line-2.js
test/annexB/language/comments/single-line-html-close-first-line-3.js
```
If executed without `harness/sta.js`, these tests will fail with `ReferenceError: Test262Error is not defined` instead. Therefore, the `raw` flag should be removed from these tests.

### PR DESCRIPTION
**Pull request by Boshen**
closes #4020

Updated the tests per https://github.com/tc39/test262/issues/4020#issuecomment-2009885892

### CODE REVIEW

**Comment by Boshen** [comment]
Discovered this test case while setting up runtime execution tests in Oxc.

**Review by ptomato — CHANGES_REQUESTED** [review]
Thanks for the PR!

I think these will still fail because the `negative` key in the front matter says to expect a Test262Error. (see https://github.com/tc39/test262/blob/HEAD/CONTRIBUTING.md#negative)

I'd suggest throwing a built-in error type, preferably not SyntaxError since that might be accidentally thrown otherwise in the parse phase. Probably Error is fine.

**Comment by Boshen** [comment]
Learned how to verify with test262-harness:

```
test262-harness  master ❯ ./bin/run.js --host-type node --host-path `which node` ~/github/test262/test/annexB/language/comments/*.js
Ran 13 tests
13 passed
0 failed
```

**Comment by ljharb** [comment]
(fwiw in tests I love using EvalError for a builtin error type that isn't likely to come from anything but the test)

**Comment by Boshen** [comment]
I changed to `EvalError`. Verified with `test262-harness`.

**Comment by ptomato** [comment]
Thanks! EvalError works too.

**Review by ptomato — APPROVED** [review]

**Pull request merged**
