### PR TITLE
Sync Intl Locale API tests w/ PR67

### PR DESCRIPTION
**Pull request by FrankYFTang**
change the tests to sync with 

https://github.com/tc39/proposal-intl-locale-info/pull/67

### CODE REVIEW

**Comment by FrankYFTang** [comment]
@ryzokuken @sffc @romulocintra

**Review by gibson042 — APPROVED** [review]

**Comment by ptomato** [comment]
@FrankYFTang I believe this is ready, and the normative change has consensus and has been merged. It looks like some `output-array-values.js` tests have been added in the meantime to some of the folders that this PR removes, though. Could you look at whether those need to be moved those to the new folders?

**Comment by CanadaHonk** [comment]
This fixes #3746.

**Comment by FrankYFTang** [comment]
rebased PTAL

**Review by Ms2ger — APPROVED** [review]

**Pull request merged**
