### PR TITLE
Update tests for TypedArrays/DataView non-interoperable get accessor methods

### PR DESCRIPTION
**Pull request by leobalter**
Closes gh-582

### CODE REVIEW

**Comment by jugglinmike** [comment]
This looks good to me, although we should add `features: [DataView]` to the three tests that now require the DataView constructor.

**Comment by leobalter** [comment]
done

**Comment by goyakin** [comment]
Merged as a4fd0dc8f4de5244322d3b017f77e46ecfa3a3c0.

**Comment by leobalter** [comment]
Thanks, @goyakin! Welcome back!

**Pull request closed without merging**
