### PR TITLE
Fix expectation in disambiguation-wrong-type.js

### PR DESCRIPTION
**Pull request by FrankYFTang**
@Ms2ger @ptomato @ryzokuken @jugglinmike

### CODE REVIEW

**Comment by jugglinmike** [comment]
This test looks correct to me as it is written. Can you share your rationale for suggesting this change?

(It's generally a good practice to include that kind of information in the commit message so that, if the patch is accepted, its justification is accessible to others in the project's revision history.)

**Comment by FrankYFTang** [comment]
epochNanoseconds of Temporal.ZonedDateTime should return the same value as the epochNanoseconds passed in in the constructor. The current expectation is simply different.

**Comment by ptomato** [comment]
I agree with @jugglinmike here, I believe the test is correct as written. The epochNanoseconds property being tested here isn't set by the constructor, it's tested on the result of the call to `with()`.

**Comment by FrankYFTang** [comment]
sorry, I got confused.

**Pull request closed without merging**
