### PR TITLE
 proposal-regexp-modifiers: Tests for syntax errors

### PR DESCRIPTION
**Pull request by guijemont**
This covers the syntax error cases from https://github.com/tc39/test262/issues/3756.
This is an updated version of https://github.com/tc39/test262/pull/3758 addressing review comments.

### CODE REVIEW

**Comment by guijemont** [comment]
The main issue why this is still a work in progress, is that the templated test generator has some issues.
In particular, we want to use it with templates such as:
```javascript
/(?/*{ subpattern-add-modifiers }*/-/*{ subpattern-remove-modifiers }*/:a)//*{ global-modifiers }*/;
```

But the generator cannot replace `/*{ global-modifiers }*/` as it seems to consider that `//*{ global-modifiers }*/;` is a comment. In otherwords, the generator needs to learn about how to handle comments that immediately follow a regex literal.

**Comment by guijemont** [comment]
> The main issue why this is still a draft, is that the templated test generator has some issues. In particular, we want to use it with templates such as:
> 
> ```js
> /(?/*{ subpattern-add-modifiers }*/-/*{ subpattern-remove-modifiers }*/:a)//*{ global-modifiers }*/;
> ```
> 
> But the generator cannot replace `/*{ global-modifiers }*/` as it seems to consider that `//*{ global-modifiers }*/;` is a comment. In otherwords, the generator needs to learn about how to handle comments that immediately follow a regex literal.

I created issue https://github.com/tc39/test262/issues/3808 to report the problem.

**Review by rbuckton — COMMENTED** [review]
This looks good as far as invalid syntax coverage is concerned, at least once #3808 is resolved.

**Comment by ptomato** [comment]
Closing in favour of #4016.

**Pull request closed without merging**
