### PR TITLE
Add basic tests for proposal-intl-locale-info

### PR DESCRIPTION
**Pull request by ryzokuken**
Add the basic tests (`name.js`, `branding.js` and `prop-desc.js`) for the Intl LocaleInfo proposal.

The existing getters on the `Intl.Locale` prototype only have these basic tests as well, so I think this should be sufficient for unblocking implementations. That said, I will try to add more comprehensive tests for these getters.

/cc @FrankYFTang

Fixes: #2984

### CODE REVIEW

**Review by Ms2ger — DISMISSED** [review]

**Comment by FrankYFTang** [comment]
Since Intl Locale info is a newer proposal than 
```
# Intl.Locale
# https://github.com/tc39/proposal-intl-locale
Intl.Locale
```
I suggest you add to 
https://github.com/tc39/test262/blob/main/features.txt
```
# Intl.Locale-info
# https://github.com/tc39/proposal-intl-locale-info
Intl.Locale-info
```

and change
```
features: [Intl.Locale]
```
to
```
features: [Intl.Locale,Intl.Locale-info]
```
so each browser can decide which flag to turn in their test framework based on that.

**Comment by ryzokuken** [comment]
@FrankYFTang thanks, done. PTAL.

**Comment by FrankYFTang** [comment]
LGTM. I think we need more test to ensure the return data type fit the spec but that could come from a later PR.

**Comment by ryzokuken** [comment]
> I think we need more test to ensure the return data type fit the spec but that could come from a later PR.

That's precisely what I'm planning :smile:

**Review by jugglinmike — COMMENTED** [review]
Thanks for the patch! When we land it, I'll create a tracking issue for the follow-up you had in mind so folks know that it's a work-in-progress.

Runtimes that don't implement this API will spuriously pass the "branding" tests--they will report a `TypeError` due to `propdesc.call` being undefined. Would you mind adding an assertion to guard against that?

```
assert.sameValue(typeof propdesc.get, "function");
```

**Comment by ryzokuken** [comment]
@jugglinmike thanks, done, check it out. Should I make another PR to add those for the original `Intl.Locale` getters too?

**Comment by FrankYFTang** [comment]
LGTM

**Review by FrankYFTang — APPROVED** [review]

**Comment by jugglinmike** [comment]
> @jugglinmike thanks, done, check it out. Should I make another PR to add those for the original `Intl.Locale` getters too?

That would be wonderful!

**Review by jugglinmike — APPROVED** [review]

**Pull request merged**
