### PR TITLE
Update tests to match latests drafts

### PR DESCRIPTION
**Pull request by anba**
Tests doesn't use async functionality and don't call $DONE, so remove "async" flag:
- src/params/error/async-gen-named-func-expr.template
- test/language/expressions/async-generator/params-named-dflt-abrupt.js
- test/language/expressions/async-generator/params-named-dflt-ref-later.js
- test/language/expressions/async-generator/params-named-dflt-ref-self.js

Intl.PluralRules.prototype is no longer a Intl.Prototype instance:
- test/intl402/PluralRules/prototype/prototype.js

Intl.PluralRUles throws an error when called as a function:
- test/intl402/PluralRules/undefined-newtarget-throws.js

Module namespace objects call OrdinaryDelete for symbol properties:
- test/language/module-code/namespace/internals/delete-non-exported.js

Async generators no longer retrieves "done" property twice:
- test/language/statements/async-generator/yield-star-async-next.js
- test/language/statements/async-generator/yield-star-async-return.js
- test/language/statements/async-generator/yield-star-async-throw.js

Minor units of CLF is 4, so we need to test with maximumFractionDigits=3 to get an error:
- test/intl402/NumberFormat/dft-currency-mnfd-range-check-mxfd.js

### CODE REVIEW

**Comment by leobalter** [comment]
Thanks for this. It means I also need to update #937 to reflect the "Async generators no longer retrieves "done" property twice" part.

**Comment by anba** [comment]
Added a missing update for test/intl402/DateTimeFormat/prototype/formatToParts/length.js per https://github.com/tc39/ecma402/pull/138.

**Comment by anba** [comment]
And updated again to fix test/intl402/NumberFormat/11.1.1_32.js per https://github.com/tc39/ecma402/pull/139.

**Comment by rwaldron** [comment]
@anba needs rebase—thanks!!

**Comment by leobalter** [comment]
@anba some tests are now using the test generation tool. Do you mind updating these on the respective templates or I can do it after your changes if you prefer.

**Comment by leobalter** [comment]
you can find the respective templates/cases in the files showing with a conflict.

**Comment by anba** [comment]
> @anba some tests are now using the test generation tool. Do you mind updating these on the respective templates or I can do it after your changes if you prefer.

Actually I did update the template and then I ran make.py. Are there more steps required?

**Comment by leobalter** [comment]
> Actually I did update the template and then I ran make.py. Are there more steps required?

the files `test/language/statements/async-generator/yield-star-*` are now generated with the other PRs merged today. You can find the respective cases at `src/async-generators/yield-star-async-*.case`.

**Comment by anba** [comment]
Ah, okay - there was a misunderstanding on my part. I thought this was about the files generated from async-gen-named-func-expr.template.

**Comment by leobalter** [comment]
> Ah, okay - there was a misunderstanding on my part. I thought this was about the files generated from async-gen-named-func-expr.template.

Yes, I saw those as well.

I fixed them here, I'm merging it soon.

**Comment by anba** [comment]
> I fixed them here, I'm merging it soon.

Great, thanks! 😄

**Comment by leobalter** [comment]
Thank __you__ for the fixes!

**Pull request closed without merging**
