### PR TITLE
Add tests for accessor names in object initializer

### PR DESCRIPTION
**Pull request by jugglinmike**
This should resolve gh-703. What do you think, @avdg?

### CODE REVIEW

**Comment by avdg** [comment]
Looking generally very good, although there are lots of 0 and 1 used in the numbers.

**Comment by avdg** [comment]
Hmmm... classes should also be covered as well I guess

**Comment by avdg** [comment]
And set seems to accept a BindingElement as parameter.

**Comment by avdg** [comment]
(there are some tests though at https://github.com/tc39/test262/tree/master/test/language/computed-property-names/class/accessor)

**Comment by jugglinmike** [comment]
Superseded by gh-843. Thanks for keeping me honest, @avdg.

**Comment by avdg** [comment]
Np

**Pull request closed without merging**
