### PR TITLE
Add minimal documentation for features flags

### PR DESCRIPTION
**Pull request by leobalter**

### CODE REVIEW

**Comment by littledan** [comment]
Would it make sense to note that, when adding tests for a new proposal, that it's a good idea to add a new feature flag?

**Comment by leobalter** [comment]
@littledan I believe there's a lot to improve in this document. My limited time allowed me only start it. 

> it's highly recommended to reuse the features flags for any matching case in new tests.

That's the part where I'm basically saying I'll ask for feature flags in new tests. My goal, but not for this PR, is to make it a requirement for any stage 3 proposal. I'm avoiding discussions that might block shipping the current text.

**Comment by littledan** [comment]
Sure, this text is better than no text; I don't want to slow you down!

**Comment by leobalter** [comment]
I'm adding this file as we should continue working on top of it.

>Would it make sense to note that, when adding tests for a new proposal, that it's a good idea to add a new feature flag? 

@littledan I want to make this a requirement, I'll open another PR this week to get feedback, but I believe we're gonna be fine on this.

**Pull request merged**
