### PR TITLE
compare "numeric" as boolean instead of string

### PR DESCRIPTION
**Pull request by FrankYFTang**
https://tc39.github.io/proposal-intl-locale/#sec-Intl.Locale
36. If relevantExtensionKeys contains "kn", then
 a. Set locale.[[Numeric]] to ! SameValue(r.[[kn]], "true").
and then
https://tc39.github.io/proposal-intl-locale/#sec-Intl.Locale.prototype.numeric
Intl.Locale.prototype.numeric 
3. Return loc.[[Numeric]].

so it should be a boolean, not a string of "true" or "false"

### CODE REVIEW

**Comment by FrankYFTang** [comment]
This was broke by https://github.com/tc39/test262/pull/1798/ 
@leobalter @rwaldron @Ms2ger

**Comment by FrankYFTang** [comment]
Also notice https://github.com/tc39/test262/blob/master/test/intl402/Locale/getters.js it is correctly comparing with true and false not "true" and "false".

**Comment by FrankYFTang** [comment]
The change is needed to reflect the change in the spec https://github.com/tc39/proposal-intl-locale/commit/cf84ee38db6af3c02feda5010ad32735bb558e99#diff-3540caefa502006d8a33cb1385720803

**Comment by FrankYFTang** [comment]
this is because the test currently reflect the old spec, without changing with https://github.com/tc39/proposal-intl-locale/issues/55

**Comment by littledan** [comment]
Thanks for the fix, Frank. Has anyone followed up with the remaining changes? @Ms2ger?

**Pull request merged**
