### PR TITLE
Add test for firstDayOfWeek in LocaleInfo PR 70

### PR DESCRIPTION
**Pull request by FrankYFTang**
Test for enhancement in
https://github.com/tc39/proposal-intl-locale-info/pull/70

### CODE REVIEW

**Comment by FrankYFTang** [comment]
please add "awaiting specification" label

**Comment by FrankYFTang** [comment]
PR70 is merged after reach consensus on TC39 2023-09-26 meeting.

**Comment by FrankYFTang** [comment]
Please review and merge. Thanks

**Review by ptomato — APPROVED** [review]
Thanks!

**Comment by ptomato** [comment]
For some reason, GitHub is acting weird about displaying the status. I hope the PR will merge itself eventually with auto-merge enabled.

**Pull request merged**
