### PR TITLE
Add tests for %TypedArray%.prototype.{reduce,reduceRight}

### PR DESCRIPTION
**Pull request by leobalter**

### CODE REVIEW

**Comment by jugglinmike** [comment]
There are a few occurrences of the word "interaction" that ought to be
"iteration." Obviously this doesn't effect test validity, but "iteration" is a
more precise term here.

The tests themselves look great :)

**Comment by leobalter** [comment]
fixed at 66a0cec w/ extras 3cf10be

**Comment by jugglinmike** [comment]
Thanks!

**Comment by jugglinmike** [comment]
Merged to `master` at commits dfbf33b3acd59db01a340f2194fe1bfddd9d6d8c & ba31c4da9c83e2a18b082f26f0006a426464f8d7. Whoopie!

**Pull request closed without merging**
