### PR TITLE
monkeyYaml: Add support for line folding

### LINKED ISSUE #345: monkeyYaml is confused
monkeyYaml fails on https://github.com/tc39/test262/blob/master/test/built-ins/Object/assign/ObjectOverride-sameproperty.js with the error mesage

```
Traceback (most recent call last):
  File "/mnt/data/b/build/slave/linux/build/v8/tools/run-tests.py", line 692, in <module>
    sys.exit(Main())
  File "/mnt/data/b/build/slave/linux/build/v8/tools/run-tests.py", line 518, in Main
    code = Execute(arch, mode, args, options, suites, workspace)
  File "/mnt/data/b/build/slave/linux/build/v8/tools/run-tests.py", line 618, in Execute
    for v in s.VariantFlags(t, variant_flags) ]
  File "/mnt/data/b/build/slave/linux/build/v8/test/test262-es6/testcfg.py", line 86, in VariantFlags
    test_record = self.GetTestRecord(testcase)
  File "/mnt/data/b/build/slave/linux/build/v8/test/test262-es6/testcfg.py", line 114, in GetTestRecord
    testcase.path)
  File "/mnt/data/b/build/slave/linux/build/v8/test/test262-es6/data/tools/packaging/parseTestRecord.py", line 106, in parseTestRecord
    yamlAttrParser(testRecord, attrs, name)
  File "/mnt/data/b/build/slave/linux/build/v8/test/test262-es6/data/tools/packaging/parseTestRecord.py", line 81, in yamlAttrParser
    parsed = yamlLoad(body)
  File "/mnt/data/b/build/slave/linux/build/v8/test/test262-es6/data/tools/packaging/monkeyYaml.py", line 33, in load
    raise Exception("monkeyYaml is confused at " + line)
Exception: monkeyYaml is confused at              i.e. a later assignment to the same property overrides an earlier assignment.
```

@smikes

### PR DESCRIPTION
**Pull request by arv**
Fixes #345

### CODE REVIEW

**Comment by arv** [comment]
@jugglinmike @smikes PTAL

**Comment by arv** [comment]
@littledan FYI

**Comment by jugglinmike** [comment]
Looks good to me!

**Comment by bterlson** [comment]
Since this is blocking Goog and I'm on vacation with intermittent access, I'm going to pull this in now. I'll expect a follow-up PR fixing the whitespace issues :)

**Comment by smikes** [comment]
Sounds good.

**Pull request merged**
