### PR TITLE
Add `/iu` Unicode case folding tests

### PR DESCRIPTION
**Pull request by mathiasbynens**
Ref. https://bugs.chromium.org/p/v8/issues/detail?id=13377

### CODE REVIEW

**Review by ptomato — DISMISSED** [review]
Thanks! After reading the Chromium bug and digging into the CompileToCharSet operation and CaseFolding.txt, I think I understand what's going on here, and I concur. These six code points all have an "F" for Full case mapping in CaseFolding.txt, and so they should not be considered in the Canonicalize operation.

This is fine as-is, but for maximum usefulness, would you consider putting a test in the main tree e.g. somewhere in `test/built-ins/RegExp/`? (Or otherwise in staging so that it can be moved into the main tree eventually) I don't know how many other engines regularly execute the `implementation-contributed/` tests.

**Review by ptomato — APPROVED** [review]
Re-approving

**Comment by ptomato** [comment]
I'll merge this and open a new PR to add this to the main tree as well.

**Comment by mathiasbynens** [comment]
> I'll merge this and open a new PR to add this to the main tree as well.

Cheers!

**Pull request merged**
