### PR TITLE
make Object / property tests work with testStrict=true

### PR DESCRIPTION
**Pull request by smikes**
First 34 completed (see PR).  working on rest

### CODE REVIEW

**Comment by anba** [comment]
Reviewed and tested, looks good!

**Comment by bterlson** [comment]
Awesome!!

**Comment by bterlson** [comment]
And you got rid of runTestCase in a bunch of cases :-D

**Comment by anba** [comment]
Something went wrong with this PR. The commit 78a3fe4db60d38e79a131e637c91e3f9d370f0ed added invalid updates (most likely WIP code?) for Object.{defineProperty, defineProperties} in addition to the 34 updates for Object.create.

**Comment by smikes** [comment]
Yes, the commit was not yet ready to go when it was patched in.  Is this not fixed by #255?  I will take a look later today.

**Comment by anba** [comment]
> Is this not fixed by #255?

I still need to review/test that PR.

**Comment by bterlson** [comment]
Gah sorry... I got a little eager.

**Pull request merged**
