### PR TITLE
[WIP] for-await-of: dstr-assignment, templates & cases

### PR DESCRIPTION
**Pull request by rwaldron**

### CODE REVIEW

**Comment by rwaldron** [comment]
Not ready for review

**Comment by leobalter** [comment]
no problem, ping here when it's ready.

**Comment by leobalter** [comment]
These are still missing the respective generated tests.

**Comment by rwaldron** [comment]
> These are still missing the respective generated tests.

I decided to do this in a follow up PR that moved them to the correctly named directory—instead of generating tests, moving the source, deleting the tests and then generating the tests.

**Comment by leobalter** [comment]
That's reasonable, thanks for the clarification.

**Pull request merged**
