### PR TITLE
Add presence check for property cause on Error.prototype

### PR DESCRIPTION
**Pull request by legendecas**
Property `cause` should not present on `Error.prototype`.

### CODE REVIEW

**Review by rwaldron — CHANGES_REQUESTED** [review]
- Some of this duplicates existing tests. 
- Please put these in separate files, in the appropriate directories (where you will find that some of this is already covered)

**Comment by jugglinmike** [comment]
Thanks for the patch! [Hosts are permitted to define an `Error.prototype.cause` property](https://tc39.es/ecma262/#sec-host-built-in-objects-and-methods), so we should remove the assertion for its absence.

**Comment by legendecas** [comment]
Thanks for the suggestions! Well, I didn't notice that there are statements about host extensions on built-in objects. I was noticing v8 is putting a `cause` with `undefined` value on `Error.prototype` which is not expected. If spec allows such extension, I'd close this PR and just file a bug to v8.

**Comment by ljharb** [comment]
I added https://github.com/tc39/agendas/commit/964d2d36f80994b1b77972ef4867c8569b531874 to the next meeting to discuss tightening restrictions on hosts, so that helpful tests like this can be permitted.

**Comment by leobalter** [comment]
@ljharb can you share what do you suggest/recommend as the next steps for the restrictions?

The issue on this one is that ECMAScript allows extensions. This is imperative as globals add names for the platform it is contained, and other names are not exactly defined by ECMAScript. Otherwise, it would be easy to enumerate the names expected in `Error.prototype`, but if the host adds anything (not limited to `cause`), how is that an error?

**Comment by ljharb** [comment]
Allowing new globals, as well as property names on any object that are *not* specified in 262 or 402, is fine.

My hope is that we can forbid extensions on any specified objects whose names are specified elsewhere in 262 or 402, which would include “cause” on any language builtins other than the specified ones.

**Pull request closed without merging**
