### PR TITLE
Revert "Additional tests for QuantifiableAssertion"

### PR DESCRIPTION
**Pull request by leobalter**
Reverts tc39/test262#1456

pending on Needs consensus

### CODE REVIEW

**Comment by leobalter** [comment]
cc @littledan. You may land it again after consensus.

**Comment by littledan** [comment]
LGTM

**Comment by leobalter** [comment]
@littledan would you mind to open a new PR with the same tests? We can use the revert button here, reverting the revert. Than we flag it to wait for the respective consensus.

**Comment by littledan** [comment]
@leobalter Created in https://github.com/tc39/test262/pull/1459 .

**Comment by leobalter** [comment]
thanks!

**Pull request merged**
