### PR TITLE
Add tests for return value of @@species accessors

### PR DESCRIPTION
**Pull request by jugglinmike**

### CODE REVIEW

**Comment by leobalter** [comment]
We could add tests for missing prop-desc, asserting the _set_ accessor is __undefined__ as in [here](https://github.com/tc39/test262/blob/master/test/built-ins/Promise/Symbol.species/prop-desc.js)

**Comment by jugglinmike** [comment]
Hey Leo: I've added the assertions that you requested.

**Comment by leobalter** [comment]
LGTM

**Comment by goyakin** [comment]
Merged as 85e6ab8.

**Pull request closed without merging**
