### PR TITLE
Add and update tests for String.prototype.endsWith

### PR DESCRIPTION
**Pull request by leobalter**

### CODE REVIEW

**Comment by jugglinmike** [comment]
Only one piece of feedback for this one: in `test/built-ins/String/prototype/endsWith/return-false-with-out-of-bounds-start.js`, the file name and description do not match the behavior under test. Otherwise, looks good!

**Comment by leobalter** [comment]
rebased the branch due to conflicts with updates on master.

I didn't squash the fixup commits yet.

**Comment by bterlson** [comment]
Looks good, feel free to squash!

**Comment by leobalter** [comment]
rebased and :eggplant:'ed

**Pull request merged**
