### PR TITLE
test: Add test for private method in object literal

### PR DESCRIPTION
**Pull request by jbhoosreddy**
Tracking Issue: #1343

### Summary of changes:
- Add tests for private method in object literal

### CODE REVIEW

**Comment by jbhoosreddy** [comment]
@rwaldron @leobalter for review

not really sure if that's the right place to even put these tests. thoughts?

**Comment by rwaldron** [comment]
These need to be moved: 

`test/language/literals/object/` => `test/language/expressions/object/method-definition/`

**Comment by jbhoosreddy** [comment]
@rwaldron for review

**Comment by rwaldron** [comment]
I want to think more about this changeset. I have two concerns: 

1. I want to welcome your contribution, because you put in the work and that should be recognized. However...
2. It occurred to me that tests like this are generally avoided because it's hard to tell where the "coverage boundary" begins and ends, ie. what part of the spec is this actually testing? The obvious answer is that it's testing to ensure that _PrivateName_ is not allowed inside _PropertyDefinitionList_—but I'd counter that a lot of things aren't allowed inside _PropertyDefinitionList_... for example, Python code (that's a bit extreme, but I think it illustrates well).

Let's think about this a bit more.

**Comment by jbhoosreddy** [comment]
@rwaldron I don't mind scrapping this PR. If we decide we don't want to cover these, do you mind updating the test plan linked to the PR?

**Comment by littledan** [comment]
We previously considered such "private name shorthand", e.g., in https://github.com/littledan/proposal-private-shorthand , and decided to break it out into a separate, follow-on proposal. I think it's worth it to have a test that it is not supported, given that history. (Related: https://github.com/tc39/test262/pull/1782#issuecomment-425483531)

**Comment by jbhoosreddy** [comment]
similar to #1782. closing

**Comment by littledan** [comment]
Note, the lack of these tests  led to a delay in discovering a real issue in the V8 implementation of private fields and methods: https://chromium-review.googlesource.com/c/v8/v8/+/1461161 . I'd ask you to reconsider whether such tests are OK. Note that the recently committed `super.#x` tests are a similarly specified case of the grammar not having a particular production for it, not an early error. cc @gsathya

**Pull request closed without merging**
