### PR TITLE
use all values max and min fraction and significant digits

### PR DESCRIPTION
**Pull request by romulocintra**
Summary : 

WIP updating https://github.com/tc39/test262/issues/3364 

Will be draft PR depending on: https://github.com/tc39/proposal-intl-numberformat-v3/issues/81 that could also affect the tests

### CODE REVIEW

**Comment by rwaldron** [comment]
LGTM, ping when out of draft mode

**Comment by romulocintra** [comment]
> LGTM, ping when out of draft mode

Thanks for having a look at it, will leave it like this and do incremental coverage as it covers  #3364

**Review by sffc — APPROVED** [review]

**Review by ptomato — APPROVED** [review]
This test seems correct according to https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/proposed.html#sec-setnfdigitoptions

According to #3364 the idea was to add tests for different values of `roundingPriority`. Is that still planned to be added in another PR?

**Comment by romulocintra** [comment]
> This test seems correct according to https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/proposed.html#sec-setnfdigitoptions
> 
> 
> 
> According to #3364 the idea was to add tests for different values of `roundingPriority`. Is that still planned to be added in another PR?

Yes that's the idea add those in a new PR

**Comment by ptomato** [comment]
OK, thanks!

**Pull request merged**
