### PR TITLE
`Promise` methods should not be enumerable

### PR DESCRIPTION
**Pull request by ljharb**
`Promise` methods should not be enumerable, per https://people.mozilla.org/~jorendorff/es6-draft.html#table-4

### CODE REVIEW

**Comment by domenic** [comment]
This should use the verifyNotEnumerable helpers

**Comment by ljharb** [comment]
aha, thanks, wasn't aware those existed. will update.

**Comment by rwaldron** [comment]
LGTM

**Comment by bterlson** [comment]
LGTM too.

**Comment by ljharb** [comment]
Thanks!

**Pull request merged**
