### PR TITLE
Remove 'AsyncArrowFunction' test

### LINKED ISSUE #4044: Remove non-existend "AsyncArrowFunction" constructor
Same as https://github.com/tc39/test262/commit/04517c7dedc968a4e1677088bc57773c61699f6d, `AsyncArrowFunction` doesn't exist.

### PR DESCRIPTION
**Pull request by linusg**
Fixes #4044

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Review by Ms2ger — CHANGES_REQUESTED** [review]
Please ensure there is a test that `Object.getPrototypeOf(async () => {})` and `Object.getPrototypeOf(async function () {})` match.

**Comment by nicolo-ribaudo** [comment]
There is an implementation-contributed one at https://github.com/tc39/test262/blob/6c60904d42b4872a3aa1224fc7ad2c4c733e9685/implementation-contributed/v8/mjsunit/es8/async-await-basic.js#L82-L93

**Comment by ptomato** [comment]
This ties into something else I've been trying to figure out; do implementations actually execute those implementation-contributed tests?

**Comment by anba** [comment]
> [...] do implementations actually execute those implementation-contributed tests?

No, because the tests contain implementation internal functions and syntax.

**Comment by ptomato** [comment]
@linusg We deleted the implementation-contributed folder because it couldn't be run by other implementations anyway, so could you add the test that Ms2ger requested? Otherwise this seems ready to merge.

**Comment by linusg** [comment]
Thanks for the ping, I'll try to do that ASAP.

**Comment by linusg** [comment]
Done, PTAL!

**Review by Ms2ger — APPROVED** [review]

**Pull request merged**
