### PR TITLE
[WIP] Early Errors > Grammar #1343

### PR DESCRIPTION
**Pull request by jbhoosreddy**
### Summary of changes:
- [ ] No space permitted between # and name (either in definition or usage) 🏃❓ 
- [ ] Space permitted between receiver and private method access
- [ ] "shorthand" not permitted -- a receiver is required
- [ ] Private methods not permitted in object literals
- [ ] Super private access (super.#x()) is not permitted
- [ ] Private methods may not be deleted

#### Legend
- 🏃 means it's in progress
- ❓ needinfo

### CODE REVIEW

**Comment by jbhoosreddy** [comment]
Question re/ early errors: When I try to write test cases for early errors, I run into babel parse errors which bail test262-harness. How can this be fixed? cc @littledan or others maintainers

**Comment by mkubilayk** [comment]
I'm also working on a set of early errors for private methods and hitting the same issue as @jbhoosreddy with the babel parser.

**Comment by mkubilayk** [comment]
I suspect test harness uses a version of the parser that doesn't support private methods syntax properly. 

```js
class C {
    #foo() {}
}
```

I was able to parse the code above using `@babel/parser@7.0.0-beta.55`. It didn't work with `babylon@6.18.0`, which is the version installed for `test262-harness`.

```js
const code = `
class C {
    #foo() {}
}
`;

// parses
const ast = require('@babel/parser').parse(code, {
    sourceType: 'module',
    plugins: [
        'classPrivateMethods'
    ]
});

// throws
const babylonAst = require('babylon').parse(code, {
    sourceType: 'module',
    plugins: [
        'classPrivateMethods'
    ]
});
```

It looks like `classPrivateMethods` is not a plugin available in [here](https://github.com/babel/babylon/blob/6.x/README.md#plugins).

**Comment by rwaldron** [comment]
The Babel option test262-harness is basically the worst feature ever added to that tool and shouldn't be used at all.

**Comment by rwaldron** [comment]
Also, we have tons of Class private field tests that need to be restored from git history.

**Comment by jbhoosreddy** [comment]
@rwaldron does test262 not have a way to skip tests? I'm curious why some tests need to be restored from git history? Maybe @mkubilayk and I can PR to add that feature also.

**Comment by littledan** [comment]
Great to see more progress on class field tests both in this PR as well as in https://github.com/tc39/test262/pull/1660 . I guess once #1660 lands, we can rebase these fixes on top if there is any more work to do.

I agree with the statements in the checkboxes at the top of this PR; could you explain more about what info you need about the first item, @jbhoosreddy ?

For tests against early errors with Babel, it's probably better to use @jugglinmike 's direct integration of Babylon with test262 at https://github.com/babel/babylon/pull/654 . Maybe this will be able to test the private methods grammar even if the transforms aren't ready yet (see https://github.com/babel/proposals/issues/22 -- the transform is listed as "in progress", even for Babel 7).

Thanks for your fixes to test262-harness's --babelPresets flag, @leobalter and @rwaldron . It definitely wasn't perfect on the first try, and has room for improvement still. I recommended that @jbhoosreddy develop tests for private methods using this mode, but imagined that improving the infrastructure would be part of the project as well. If this recommendation was a poor one, let's figure out the right development mode is. I saw that you marked this flag as deprecated, @rwaldron . I'm wondering, what would you recommend for running test262 tests against Babel transforms?

**Comment by rwaldron** [comment]
> I'm curious why some tests need to be restored from git history? 

Because they were removed when the spec was split and part of the features were demoted to State 2.

**Comment by littledan** [comment]
> I'd recommend using Babel's test runner for testing Babel transforms: https://github.com/babel/babel/blob/master/Makefile#L99-L100

Does this test the transforms, or [just the parser](https://github.com/babel/babel/blob/master/scripts/tests/test262/run_babel_parser_test262_utils.js#L59)?

**Comment by rwaldron** [comment]
@jbhoosreddy I didn't previously recognize that this was meant to be focused on private methods—I thought it was for **all** new class field and class private (instance and static) features. So far we've been focused only on these: 

- https://tc39.github.io/proposal-class-fields/
- https://tc39.github.io/proposal-static-class-features/

Which means there is presently no coverage for: 

- https://tc39.github.io/proposal-private-methods/

**Comment by rwaldron** [comment]
@jbhoosreddy please add `class-methods-private` to features.txt and make sure that the feature appears in all relevant tests 👍

**Comment by jbhoosreddy** [comment]
I'm taking this up in #1709

**Pull request closed without merging**
