### PR TITLE
Normative: Add new numbering system "kawi" and "nagm"

### PR DESCRIPTION
**Pull request by FrankYFTang**
Adding tests for https://github.com/tc39/ecma402/pull/714

### CODE REVIEW

**Comment by Ms2ger** [comment]
Is this something that needs a feature flag? I suppose that would be painful.

**Comment by anba** [comment]
We didn't add any feature flags for past updates to the list of numbering systems: #3572, #2669, #2554

**Comment by Ms2ger** [comment]
Sounds good. @anba, do you want to check the code points? :)

**Comment by anba** [comment]
All code points seem to match:
- <https://github.com/unicode-org/cldr/blob/706d94d95c855bb281a1829488c511f99e689ecf/common/supplemental/numberingSystems.xml#L49>
- and <https://github.com/unicode-org/cldr/blob/706d94d95c855bb281a1829488c511f99e689ecf/common/supplemental/numberingSystems.xml#L71>

**Review by Ms2ger — APPROVED** [review]

**Pull request merged**
