### PR TITLE
Remove harness/runTestCase.js

### PR DESCRIPTION
**Pull request by anba**
Can be applied after #413, #415 and #416 are pulled in.

### CODE REVIEW

**Comment by anba** [comment]
Missed a couple of files in the annexB directory. These still need to be updated before runTestCase.js can be removed.

**Comment by rwaldron** [comment]
All set https://github.com/tc39/test262/commit/03d2f68c9c185970a9b7cee5806e8733188db360

**Comment by anba** [comment]
> All set 03d2f68

Thanks @rwaldron !

**Comment by rwaldron** [comment]
@anba no problem & thank you for doing all the cleanup work for this

**Pull request merged**
