### PR TITLE
Move test which depends on TimeZone to intl402

### PR DESCRIPTION
**Pull request by FrankYFTang**
Temporal proposal only require the implementation to support "UTC" TimeZone unless they also support ECMA402, therefore, we have to move these tests to intl402.

### CODE REVIEW

**Comment by rwaldron** [comment]
@FrankYFTang sorry, can you fix the conflict? Thanks!

**Comment by FrankYFTang** [comment]
resolve conflicts

**Comment by rwaldron** [comment]
@ptomato I'm going to hold off on merging until I get a signal from you. Have you done the work you described on Oct 29?

**Comment by ptomato** [comment]
@rwaldron I haven't had a chance to do that yet, sorry. How high is the priority on your side? I'll try to prioritize it accordingly.

**Comment by rwaldron** [comment]
@ptomato it's "whenever you get to it" ;)

**Comment by ptomato** [comment]
@rwaldron I've opened https://github.com/tc39/test262/pull/3377 for that, I think we can consider it to supersede this PR.

**Comment by ptomato** [comment]
I believe this can be closed now.

**Pull request closed without merging**
