### PR TITLE
More test cases for dynamic import

### PR DESCRIPTION
**Pull request by leobalter**
https://github.com/tc39/test262/issues/1164

### CODE REVIEW

**Comment by leobalter** [comment]
WIP, there are a few broken tests I need to fix (next week)

**Comment by leobalter** [comment]
This should be good for now.

@jdalton, would you like to review these tests?

**Comment by jdalton** [comment]
At first glance, and run, things look good. I need to update my test runner to account more for the script goal. Once I do that I can see if there is anything unexpected.

**Comment by jdalton** [comment]
Ok, updated my runner and all looks good!

**Comment by leobalter** [comment]
Cool! I'll get these landing for now (maybe I'll get more feedback after it's used in other implementations).

I can also confirm they are passing on V8 and JSC.

**Pull request merged**
