### PR TITLE
Remove ChakraCore CI job

### PR DESCRIPTION
**Pull request by ptomato**
Installation of ChakraCore by ESVU for some reason has been flaky for quite a long time. Can't reproduce locally. This CI job doesn't add much value by itself, so just remove it until some future time.

Closes: #3953

### CODE REVIEW

**Comment by ljharb** [comment]
Should we notify chakracore's maintainers?

**Comment by ptomato** [comment]
Not sure whether it's an ESVU problem or a ChakraCore problem. (Although I see ESVU is [removing ChakraCore in the next release](https://github.com/devsnek/esvu/commit/99600f18e3b19608d79037a7c9bbb0c437118874))

**Comment by ptomato** [comment]
Seems to be a known problem for which a PR has been open for 9 months: https://github.com/chakra-core/ChakraCore/pull/6932

**Comment by ljharb** [comment]
cc @rhuanjl on both issues.

**Review by ljharb — APPROVED** [review]

**Review by Ms2ger — APPROVED** [review]

**Comment by rhuanjl** [comment]
Thanks for the tag; @ljharb  I'll aim to merge a fix for the mentioned issue in CC; it's sad to see CC support being dropped in other places, though as is probably obviously, CC is largely a dead project these days.

I don't have nearly the time/scope to maintain it properly alone (I have a completely unrelated - not-programming - full time job) and I'm not aware of anyone with enough time who has the knowledge/interest.

I'd love to help CC be revived and used again if there is ever significant interest from others willing to throw some significant time at it, please do continue to tag me if/when anything relevant to CC is said or done.

**Comment by ptomato** [comment]
@rhuanjl ESVU removed ChakraCore support and that's what we use to install the interpreters used for CI... I think the next step would be to get it re-added there. I'll open an issue and tag you.

**Comment by ptomato** [comment]
→ https://github.com/devsnek/esvu/issues/56

**Pull request merged**
