### PR TITLE
Apply feedback for RegExp.prototype.flags

### PR DESCRIPTION
**Pull request by leobalter**
Ref #1149

### CODE REVIEW

**Comment by rwaldron** [comment]
```
test/built-ins/RegExp/prototype/flags/coercion-dotall.js: FEATURES - Unrecognized feature: "regexp-dotAll"
```

**Comment by rwaldron** [comment]
Needs to be `regexp-dotall`

**Comment by leobalter** [comment]
Oops

**Comment by leobalter** [comment]
done

**Pull request merged**
