### PR TITLE
Fix incorrect generator syntax (#761)

### PR DESCRIPTION
**Pull request by JosephPecoraro**

### CODE REVIEW

**Comment by rwaldron** [comment]
I posted the CLA link in the issue you opened, but here it is again: http://tc39.github.io/test262-cla/ please ping me back here when you've signed it. Thanks!!

**Comment by JosephPecoraro** [comment]
Err, I signed this a few weeks ago. Sorry for not pinging back.

**Comment by tcare** [comment]
@rwaldron OK to merge?

**Comment by rwaldron** [comment]
Yes definitely

**Pull request merged**
