### PR TITLE
Move the empty calendar option to the 'valid' test.

### PR DESCRIPTION
**Pull request by Ms2ger**
I misread the ABNF syntax.

### CODE REVIEW

**Comment by Ms2ger** [comment]
@littledan please confirm this is what you intended the spec to say; the inline ABNF is kinda hard to read.

**Comment by rwaldron** [comment]
@littledan I've reviewed this and am ready to land, pending your response to @Ms2ger's question

**Comment by rwaldron** [comment]
Status?

**Comment by Ms2ger** [comment]
We need to make a call on the spec issue, and then probably close this PR as no-longer-needed.

**Comment by rwaldron** [comment]
@Ms2ger thanks for the update!

**Comment by littledan** [comment]
We made the call that this case actually *should* be invalid. See https://github.com/tc39/proposal-intl-locale/pull/23#issuecomment-389355014

**Pull request closed without merging**
