### PR TITLE
Update Intl.Locale info API test

### PR DESCRIPTION
**Pull request by Constellation**
weekendStart / weekendEnd are merged into one weekend array.

### CODE REVIEW

**Comment by Constellation** [comment]
PTAL @rwaldron :)

**Comment by rwaldron** [comment]
@sffc can you review?

**Review by sffc — APPROVED** [review]
LGTM pending https://github.com/tc39/proposal-intl-locale-info/issues/51

CC @FrankYFTang

**Review by FrankYFTang — APPROVED** [review]

**Comment by Constellation** [comment]
@rwaldron OK, looks like it is r+-ed, can you merge it?

**Review by rwaldron — APPROVED** [review]

**Pull request merged**
