### PR TITLE
rename whitelist to exceptions in the linter tool

### PR DESCRIPTION
**Pull request by leobalter**

### CODE REVIEW

**Comment by leobalter** [comment]
I'll be happy to fix this later, lint tests are properly working.

**Comment by jugglinmike** [comment]
What needs fixing? Can you document that in an issue?

**Comment by leobalter** [comment]
My message was incomplete, I tried to say I would fix anything if we find problems, because I merged this without a complete review process.

I'm sorry for my miscommunication

**Comment by jugglinmike** [comment]
Got it. Thanks for clarifying!

**Pull request merged**
