### PR TITLE
Remove deprecated $ERROR function

### PR DESCRIPTION
**Pull request by chicoxyzzy**
I've replaced all `$ERROR` calls by `new Test262Error` calls, removed `$ERROR` function and its mention in `CONTRIBUTING.md` and `.jshint`

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
I forgot some more files. Will fix later tonight.

**Comment by chicoxyzzy** [comment]
Turns out `$ERROR` is actually could be useful in some cases like `executor(resolve, $ERROR);` or `}).catch($ERROR);`

**Comment by chicoxyzzy** [comment]
Maybe I should just rename `$ERROR` and don't expose for those cases?

**Comment by leobalter** [comment]
> Turns out $ERROR is actually could be useful in some cases like executor(resolve, $ERROR); or }).catch($ERROR);

That seems like cases where we would have async tests and therefore we can simply use `$DONE`,  which throws a Test262Error if called with at least one argument or called more than once. And it's successful if called once with zero arguments.

I'm looking forward for you to apply the other missing cases as I expect at least a couple extra jobs in the CI to pass here.

**Comment by leobalter** [comment]
We've got more updates in the master branch adding more `$ERROR`, please rebase. Thanks!

**Comment by rwaldron** [comment]
My concern is that there may be engine specific test suites that are overriding this function with some custom implementation.

**Comment by chicoxyzzy** [comment]
> My concern is that there may be engine specific test suites that are overriding this function with some custom implementation.

There was 2 tests (with V8 team copyright) in `test/harness/`:
- one testing that `$ERROR` throws `Test262Error`
- and second testing overriding `$ERROR`

I've removed both files.

**Comment by chicoxyzzy** [comment]
Would it be better to split this PR to a number of small PRs replacing `$ERROR` step by step?

**Comment by chicoxyzzy** [comment]
I will split this PR into a bunch of smaller PRs

**Pull request closed without merging**
