### PR TITLE
Update expected results for CLDR 42

### PR DESCRIPTION
**Pull request by anba**
Draft until CLDR 42 is published.

### CODE REVIEW

**Review by ptomato — COMMENTED** [review]
Thanks, looks reasonable for when the time comes. Do you have any link explaining the changes? I couldn't find anything about this in the draft [CLDR 42 Release Notes](https://cldr.unicode.org/index/downloads/cldr-42)

**Comment by anba** [comment]
I think the changes are from <https://unicode-org.atlassian.net/browse/CLDR-14032>.

**Comment by FrankYFTang** [comment]
Notice also the expectation in the following tests also need to be change to sync with ICU72

```
  'intl402/DateTimeFormat/prototype/formatRange/temporal-objects-resolved-time-zone': [FAIL],
  'intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-objects-resolved-time-zone': [FAIL],
  'intl402/DateTimeFormat/prototype/format/temporal-objects-resolved-time-zone': [FAIL],
  'intl402/DateTimeFormat/prototype/formatToParts/temporal-objects-resolved-time-zone': [FAIL],
  'intl402/Temporal/PlainDateTime/prototype/toLocaleString/resolved-time-zone': [FAIL],
  'intl402/Temporal/PlainTime/prototype/toLocaleString/resolved-time-zone': [FAIL],
  'staging/Intl402/Temporal/old/time-toLocaleString': [FAIL],
```

**Comment by FrankYFTang** [comment]
CLDR 42 is now published 
see https://cldr.unicode.org/index/downloads/cldr-42 could we merge this PR ASAP?

**Comment by romulocintra** [comment]
> CLDR 42 is now published see https://cldr.unicode.org/index/downloads/cldr-42 could we merge this PR ASAP?

@ptomato @Ms2ger

**Review by Ms2ger — APPROVED** [review]

**Comment by justingrant** [comment]
> Notice also the expectation in the following tests also need to be change to sync with ICU72
> 
> ```
>   'intl402/DateTimeFormat/prototype/formatRange/temporal-objects-resolved-time-zone': [FAIL],
>   'intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-objects-resolved-time-zone': [FAIL],
>   'intl402/DateTimeFormat/prototype/format/temporal-objects-resolved-time-zone': [FAIL],
>   'intl402/DateTimeFormat/prototype/formatToParts/temporal-objects-resolved-time-zone': [FAIL],
> ```

@FrankYFTang - I couldn't find these 4 tests in current Test262. Do you know where I can find them? I'm asking to make sure that they're included in glob patterns that are recognized by https://github.com/js-temporal/temporal-test262-runner/blob/main/index.mjs.

**Comment by justingrant** [comment]
Thanks @FrankYFTang for the links. I just filed https://github.com/tc39/test262/pull/3762 to fix those tests in CLDR 42. I believe that the others were already fixed by #3751.

**Pull request merged**
