### PR TITLE
Remove invalid Array.from test

### PR DESCRIPTION
**Pull request by anba**
`ArrayBuffer` cannot be constructed from an array literal and `ArrayBuffer` instances are not a valid argument value for `Array.from` (no length property, not iterable).

### CODE REVIEW

**Comment by leobalter** [comment]
LGTM

**Comment by bterlson** [comment]
Should we instead test the opposite behavior rather than deleting the test?

**Comment by leobalter** [comment]
@bterlson: I'm currently working on an update for Array.from tests, I can write this one as well.

**Comment by bterlson** [comment]
Ok cool!

**Pull request merged**
