### PR TITLE
Add branding tests from Temporal

### PR DESCRIPTION
**Pull request by ptomato**
Closes: #3137

(Ms2ger originally authored all these tests so I'm making him the author of the commit)

### CODE REVIEW

**Review by leobalter — CHANGES_REQUESTED** [review]
Please remember to add the necessary metadata so the CI can pass. Failing to do it might break existing test262 runners.

```
description: >
  Throw a TypeError if this is invalid
```

The example above should be good enough.

~~I also believe this is not exactly branding tests, the tests are verifying if `this` is invalid. Maybe calling the files `this-invalid-throws.js` would be more consistent with other Test262 tests.~~

**Comment by leobalter** [comment]
I've got corrected these are branding tests, I still have the nit pick over the test files but don't worry about changing the test file names.

**Comment by rwaldron** [comment]
> Please remember to add the necessary metadata so the CI can pass. Failing to do it might break existing test262 runners.

Yep! [`description` is required (as the contributing documentation makes clear)](https://github.com/tc39/test262/blob/main/CONTRIBUTING.md#frontmatter)

**Comment by ptomato** [comment]
OK, thanks for the review! I've added descriptions to all the files.

**Review by leobalter — APPROVED** [review]

**Pull request merged**
