### PR TITLE
Add test for private accessor methods

### PR DESCRIPTION
**Pull request by ktbee**
This PR adds templates  and generated tests for the [proposed private methods and getter/setters for JavaScript classes](https://github.com/tc39/proposal-private-methods). One issue I ran into is that single quotes are being included in generated accessor names, like in this example in `private-accessor-name-inst-computed.js`:

```
getPrivateReference() {
    return this[#'string'];
  }

setPrivateReference(value) {
    this[#'string'] = value;
}
```

One solution I was picturing was adding new variables in the case files for something like `privateDeclareWith` and `privateReferenceWith` and add the hash sign to the accessor name string there. Does that make sense or should I change this elsewhere?

### CODE REVIEW

**Comment by ljharb** [comment]
I’m confused; private fields are not allowed to be computed - ie, no bracket access whatsoever.

**Comment by leobalter** [comment]
Jordan, that’s my own fault. I was exercising Test262 templates and test
generation with Katie and asked her to open the PR. I didn’t have a proper
time to roll through the proposal yet and I missed this.

I also had some meetings until the EOD and couldn’t review the PR in time.

I’ll be back to this work and related templates on Thursday.

Thanks for reporting the issue.

**Comment by ljharb** [comment]
No worries, just wanted to make sure :-) I’ll wait to do a more thorough review.

**Comment by leobalter** [comment]
this is indeed invalid. After reviewing #1660 I'll check other parts we could reuse the templates here

**Comment by leobalter** [comment]
We can still verify getters and setters together for the same private fields, we only need to remove the computed property names out of the way.

**Comment by rwaldron** [comment]
> we only need to remove the computed property names out of the way.

Can you push the additional commits for this? Thanks!

**Comment by leobalter** [comment]
Yes I will

**Comment by leobalter** [comment]
Commits added on #1922

**Pull request closed without merging**
