### PR TITLE
Update esid for Object.getOwnPropertyDescriptors

### LINKED ISSUE #656: update esid for Object.getOwnPropertyDescriptors
`Object.getOwnPropertyDescriptors` advanced to stage 4 and we should already have a esid tag. Probably `sec-object.getownpropertydescriptor` following `Object.getOwnPropertyDescriptor`

### PR DESCRIPTION
**Pull request by leobalter**
Closes #656 

The issue I opened was unnecessary, as the change it trivial.

cc @ljharb

### CODE REVIEW

**Comment by ljharb** [comment]
This is pending https://github.com/tc39/ecma262/pull/582

**Comment by leobalter** [comment]
> This is pending tc39/ecma262#582

flagged with "future" as in System.global

**Comment by leobalter** [comment]
This can be merged now.

**Comment by jugglinmike** [comment]
Merged to `master` at commit 91d06f50b5626214a76b5c315d88cd287913e6fc.

**Pull request closed without merging**
