### PR TITLE
Fix issue with math_precision.js

### PR DESCRIPTION
**Pull request by arv**
It was missing vars which was causing issues with our test harness
since we run all the files in strict mode.

### CODE REVIEW

**Comment by arv** [comment]
@bterlson @jugglinmike PTAL

**Comment by arv** [comment]
More background: The V8 test harness runs `d8` with `--use-strict` command line flag and therefore this file fails to parse.

**Comment by jugglinmike** [comment]
This looks good to me. I don't understand how this *ever* worked in strict mode.

Also, @arv, doesn't running with `d8 --use_strict` invalidate all the tests that specify `noStrict`?

**Comment by arv** [comment]
@jugglinmike `noStrict` and `onlyStrict` are taken into account.

https://github.com/v8/v8-git-mirror/blob/master/test/test262-es6/testcfg.py#L84

**Comment by jugglinmike** [comment]
Oooh. I thought you meant you were running with `--use_strict` unconditionally, as in:

    test262.py --command "d8 --use_strict"

**Comment by arv** [comment]
We do not use the test runner provided by tc39/test262

**Pull request merged**
